# Generated by tools/fix_core_stubs.py -- do not edit by hand.
# CI regenerates this and fails on a diff.
"""
Tabulated per-element data, keyed by atomic number.
"""
from __future__ import annotations
import typing
__all__: list[str] = ['K_NUM_ELEMENTS', 'atomic_number', 'atomic_volume', 'covalent_radius', 'element_symbol', 'is_known_element']
def atomic_number(symbol: str) -> int | None:
    """
    Atomic number of a chemical symbol (case-sensitive), or None.
    """
def atomic_volume(z: typing.SupportsInt) -> float | None:
    """
    Sphere volume from the covalent radius, or None.
    """
def covalent_radius(z: typing.SupportsInt) -> float | None:
    """
    Single-bond covalent radius in angstrom, or None.
    """
def element_symbol(z: typing.SupportsInt) -> str | None:
    """
    Chemical symbol, or None.
    """
def is_known_element(z: typing.SupportsInt) -> bool:
    ...
K_NUM_ELEMENTS: int = 96
