# Generated by tools/fix_core_stubs.py -- do not edit by hand.
# CI regenerates this and fails on a diff.
"""
Raw bindings for Seitz. Import seitz instead.
"""
from __future__ import annotations
import collections.abc
import enum
import numpy
import numpy.typing
import typing
from . import elements
from . import subgroups
__all__: list[str] = ['AtomsTooCloseError', 'AxisKind', 'Cell', 'CellSetting', 'CellStandardizationFailedError', 'Centering', 'CrystalClass', 'Dataset', 'DelaunayFailedError', 'EmptyCellError', 'GroupFamily', 'HallNumber', 'Holohedry', 'InvalidLatticeError', 'K_DEFAULT_SYMPREC', 'K_LAYER_HALL_SETTINGS', 'K_NUM_LAYER_GROUPS', 'K_NUM_POINTGROUPS', 'K_NUM_SPACEGROUPS', 'K_REFERENCE_SPGLIB_VERSION', 'K_SPACE_HALL_SETTINGS', 'K_UNI_NUMBERS', 'K_VERSION', 'K_ZERO_PREC', 'Lattice', 'LatticeSetting', 'Laue', 'MagneticSymmetrySearchFailedError', 'MagneticTolerance', 'NiggliFailedError', 'Operations', 'PointGroupType', 'PointgroupNotFoundError', 'SeitzError', 'Setting', 'Site', 'SpaceGroup', 'SpacegroupMatch', 'SpacegroupSearchFailedError', 'SpacegroupType', 'SubgroupRelation', 'SymmetryAnalyzer', 'SymmetryOperation', 'SymmetryOperationSearchFailedError', 'TimeReversal', 'Tolerance', 'UniNumber', 'Version', 'Warm', 'Wyckoff', 'all_periodic', 'aperiodic_along', 'aperiodic_axis', 'conjugated_by', 'default_hall', 'default_halls_with_pointgroup', 'elements', 'family_of', 'halls_with_number', 'minimal_image', 'none_periodic', 'operations_from_database', 'periodic_along', 'pointgroup_by_number', 'same_operation', 'spacegroup_type', 'subgroups', 'to_positions', 'version_string', 'warmup', 'wrap']
class AtomsTooCloseError(SeitzError):
    """
    Two atoms closer than the distance tolerance allows. Carries .distance.
    """
class AxisKind(enum.IntEnum):
    """
    Whether a cell axis repeats.
    """
    aperiodic: typing.ClassVar[AxisKind]  # value = <AxisKind.aperiodic: 1>
    periodic: typing.ClassVar[AxisKind]  # value = <AxisKind.periodic: 0>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class Cell:
    """
    A crystal cell: a lattice, fractional positions (row i is atom i) and integer types, plus the per-axis periodicity.
    """
    def __copy__(self) -> Cell:
        ...
    def __deepcopy__(self, memo: dict) -> Cell:
        ...
    def __getitem__(self, arg0: typing.SupportsInt) -> tuple:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __init__(self, lattice: Lattice, positions: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 3]"], types: collections.abc.Sequence[typing.SupportsInt], periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"] = ...) -> None:
        ...
    def __iter__(self) -> collections.abc.Iterator:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def position(self, i: typing.SupportsInt) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def type(self, i: typing.SupportsInt) -> int:
        ...
    def with_lattice(self, lattice: Lattice) -> Cell:
        ...
    def with_periodicity(self, periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"]) -> Cell:
        ...
    @property
    def atoms(self) -> list:
        """
        The atoms as a list of (fractional position, type) pairs.
        """
    @property
    def lattice(self) -> Lattice:
        ...
    @property
    def periodicity(self) -> typing.Annotated[list[AxisKind], "FixedSize(3)"]:
        ...
    @property
    def positions(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        """
        Fractional positions as a C-contiguous (N, 3) float64 array.
        """
    @property
    def types(self) -> numpy.typing.NDArray[numpy.int32]:
        """
        Atom types as an (N,) int32 array.
        """
class CellSetting(enum.IntEnum):
    """
    Which setting a standardized cell is expressed in.
    """
    conventional: typing.ClassVar[CellSetting]  # value = <CellSetting.conventional: 0>
    primitive: typing.ClassVar[CellSetting]  # value = <CellSetting.primitive: 1>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class CellStandardizationFailedError(SeitzError):
    """
    The cell could not be brought into its standardized setting.
    """
class Centering(enum.IntEnum):
    """
    Bravais centering.
    """
    a_face: typing.ClassVar[Centering]  # value = <Centering.a_face: 4>
    b_face: typing.ClassVar[Centering]  # value = <Centering.b_face: 5>
    base: typing.ClassVar[Centering]  # value = <Centering.base: 7>
    body: typing.ClassVar[Centering]  # value = <Centering.body: 2>
    c_face: typing.ClassVar[Centering]  # value = <Centering.c_face: 6>
    error: typing.ClassVar[Centering]  # value = <Centering.error: 0>
    face: typing.ClassVar[Centering]  # value = <Centering.face: 3>
    primitive: typing.ClassVar[Centering]  # value = <Centering.primitive: 1>
    r_center: typing.ClassVar[Centering]  # value = <Centering.r_center: 8>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class CrystalClass(enum.IntEnum):
    """
    The 32 crystallographic point groups, named by Schoenflies symbol.
    """
    c1: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c1: 1>
    c2: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c2: 3>
    c2h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c2h: 5>
    c2v: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c2v: 7>
    c3: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c3: 16>
    c3h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c3h: 22>
    c3i: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c3i: 17>
    c3v: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c3v: 19>
    c4: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c4: 9>
    c4h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c4h: 11>
    c4v: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c4v: 13>
    c6: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c6: 21>
    c6h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c6h: 23>
    c6v: typing.ClassVar[CrystalClass]  # value = <CrystalClass.c6v: 25>
    ci: typing.ClassVar[CrystalClass]  # value = <CrystalClass.ci: 2>
    cs: typing.ClassVar[CrystalClass]  # value = <CrystalClass.cs: 4>
    d2: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d2: 6>
    d2d: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d2d: 14>
    d2h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d2h: 8>
    d3: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d3: 18>
    d3d: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d3d: 20>
    d3h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d3h: 26>
    d4: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d4: 12>
    d4h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d4h: 15>
    d6: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d6: 24>
    d6h: typing.ClassVar[CrystalClass]  # value = <CrystalClass.d6h: 27>
    none: typing.ClassVar[CrystalClass]  # value = <CrystalClass.none: 0>
    o: typing.ClassVar[CrystalClass]  # value = <CrystalClass.o: 30>
    oh: typing.ClassVar[CrystalClass]  # value = <CrystalClass.oh: 32>
    s4: typing.ClassVar[CrystalClass]  # value = <CrystalClass.s4: 10>
    t: typing.ClassVar[CrystalClass]  # value = <CrystalClass.t: 28>
    td: typing.ClassVar[CrystalClass]  # value = <CrystalClass.td: 31>
    th: typing.ClassVar[CrystalClass]  # value = <CrystalClass.th: 29>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class Dataset:
    """
    The result of a space-group determination. The group's identity is the Hall setting alone -- number and symbols are one lookup away through spacegroup_type().
    """
    def __repr__(self) -> str:
        ...
    @property
    def bravais(self) -> Lattice:
        ...
    @property
    def hall(self) -> HallNumber:
        ...
    @property
    def operations(self) -> Operations:
        ...
    @property
    def primitive(self) -> Lattice:
        ...
    @property
    def setting(self) -> Setting:
        ...
    @property
    def sites(self) -> list[Site]:
        ...
    @property
    def standardized(self) -> Cell:
        ...
    @property
    def std_mapping_to_primitive(self) -> list[int]:
        ...
class DelaunayFailedError(SeitzError):
    """
    Delaunay reduction failed: a degenerate cell, or a change of basis that is not unimodular.
    """
class EmptyCellError(SeitzError):
    """
    The cell has no atoms.
    """
class GroupFamily(enum.IntEnum):
    """
    The two families the determination handles: 3D space groups, and 2D-periodic layer groups.
    """
    layer: typing.ClassVar[GroupFamily]  # value = <GroupFamily.layer: 1>
    space: typing.ClassVar[GroupFamily]  # value = <GroupFamily.space: 0>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class HallNumber:
    """
    A validated Hall setting: a family plus a 1-based index into that family's settings.
    """
    @staticmethod
    def of(family: GroupFamily, index: typing.SupportsInt) -> seitz._core.HallNumber | None:
        """
        The setting, or None when `index` is out of range.
        """
    def __eq__(self, arg0: HallNumber) -> bool:
        ...
    def __ge__(self, arg0: HallNumber) -> bool:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __gt__(self, arg0: HallNumber) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __init__(self, family: GroupFamily, index: typing.SupportsInt) -> None:
        ...
    def __le__(self, arg0: HallNumber) -> bool:
        ...
    def __lt__(self, arg0: HallNumber) -> bool:
        ...
    def __ne__(self, arg0: HallNumber) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    @property
    def family(self) -> GroupFamily:
        ...
    @property
    def index(self) -> int:
        ...
class Holohedry(enum.IntEnum):
    """
    Crystal system / holohedry.
    """
    cubic: typing.ClassVar[Holohedry]  # value = <Holohedry.cubic: 7>
    hexagonal: typing.ClassVar[Holohedry]  # value = <Holohedry.hexagonal: 6>
    monoclinic: typing.ClassVar[Holohedry]  # value = <Holohedry.monoclinic: 2>
    none: typing.ClassVar[Holohedry]  # value = <Holohedry.none: 0>
    orthorhombic: typing.ClassVar[Holohedry]  # value = <Holohedry.orthorhombic: 3>
    tetragonal: typing.ClassVar[Holohedry]  # value = <Holohedry.tetragonal: 4>
    triclinic: typing.ClassVar[Holohedry]  # value = <Holohedry.triclinic: 1>
    trigonal: typing.ClassVar[Holohedry]  # value = <Holohedry.trigonal: 5>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class InvalidLatticeError(SeitzError):
    """
    A (near-)singular lattice basis, rejected before its inverse could propagate NaN through the pipeline. Carries .determinant.
    """
class Lattice:
    """
    A crystal lattice: the three basis vectors as the COLUMNS of a 3x3 matrix.
    """
    @staticmethod
    def from_basis(basis: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> seitz._core.Lattice | None:
        """
        The lattice, or None for a (near-)singular basis.
        """
    def __copy__(self) -> Lattice:
        ...
    def __deepcopy__(self, memo: dict) -> Lattice:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __init__(self, basis: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> None:
        """
        Build from a 3x3 basis whose columns are the basis vectors. Raises InvalidLatticeError if it is singular.
        """
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def delaunay(self, symprec: typing.SupportsFloat = 1e-05) -> Lattice:
        """
        Delaunay reduction; the result is right-handed.
        """
    def delaunay_in_plane(self, unique_axis: typing.SupportsInt, symprec: typing.SupportsFloat = 1e-05) -> Lattice:
        """
        2D Delaunay reduction in the plane normal to `unique_axis`.
        """
    def niggli(self, eps: typing.SupportsFloat = 1e-05) -> Lattice:
        """
        Krivy-Gruber Niggli reduction.
        """
    def rigid_rotation_to(self, ideal: Lattice) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    def to_cartesian(self, fractional: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def to_fractional(self, cartesian: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def transformed(self, t: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> Lattice:
        """
        The lattice whose columns are L . t.
        """
    @property
    def a(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        """
        First basis vector.
        """
    @property
    def b(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        """
        Second basis vector.
        """
    @property
    def c(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        """
        Third basis vector.
        """
    @property
    def matrix(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        """
        The 3x3 basis, columns = basis vectors (F-ordered).
        """
    @property
    def metric(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        """
        The metric (Gram) tensor L^T L.
        """
    @property
    def volume(self) -> float:
        ...
class LatticeSetting(enum.IntEnum):
    """
    Whether a lattice handed to a spacegroup search is the conventional cell or already a primitive one.
    """
    conventional: typing.ClassVar[LatticeSetting]  # value = <LatticeSetting.conventional: 0>
    primitive: typing.ClassVar[LatticeSetting]  # value = <LatticeSetting.primitive: 1>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class Laue(enum.IntEnum):
    """
    Laue class.
    """
    laue_1: typing.ClassVar[Laue]  # value = <Laue.laue_1: 1>
    laue_2m: typing.ClassVar[Laue]  # value = <Laue.laue_2m: 2>
    laue_3: typing.ClassVar[Laue]  # value = <Laue.laue_3: 6>
    laue_3m: typing.ClassVar[Laue]  # value = <Laue.laue_3m: 7>
    laue_4m: typing.ClassVar[Laue]  # value = <Laue.laue_4m: 4>
    laue_4mmm: typing.ClassVar[Laue]  # value = <Laue.laue_4mmm: 5>
    laue_6m: typing.ClassVar[Laue]  # value = <Laue.laue_6m: 8>
    laue_6mmm: typing.ClassVar[Laue]  # value = <Laue.laue_6mmm: 9>
    laue_m3: typing.ClassVar[Laue]  # value = <Laue.laue_m3: 10>
    laue_m3m: typing.ClassVar[Laue]  # value = <Laue.laue_m3m: 11>
    laue_mmm: typing.ClassVar[Laue]  # value = <Laue.laue_mmm: 3>
    none: typing.ClassVar[Laue]  # value = <Laue.none: 0>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class MagneticSymmetrySearchFailedError(SeitzError):
    """
    The magnetic symmetry search failed.
    """
class MagneticTolerance(Tolerance):
    """
    Tolerance plus the magnetic search's moment comparison.
    """
    def __init__(self, symprec: typing.SupportsFloat = 1e-05, angle_tolerance: typing.SupportsFloat | None = None, moment: typing.SupportsFloat | None = None) -> None:
        ...
    @property
    def moment(self) -> float | None:
        ...
    @moment.setter
    def moment(self, arg0: typing.SupportsFloat | None) -> None:
        ...
    @property
    def moment_or_symprec(self) -> float:
        ...
class NiggliFailedError(SeitzError):
    """
    Niggli reduction did not converge.
    """
class Operations:
    """
    An immutable set of space-group operations.
    """
    def __getitem__(self, arg0: typing.SupportsInt) -> SymmetryOperation:
        ...
    def __init__(self, operations: collections.abc.Sequence[SymmetryOperation]) -> None:
        ...
    def __iter__(self) -> collections.abc.Iterator[SymmetryOperation]:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def conjugated_by(self, t: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], t_inv: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> Operations:
        ...
    @property
    def empty(self) -> bool:
        ...
    @property
    def pure_translations(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]]:
        """
        The identity-rotation translations, including zero.
        """
    @property
    def rotations(self) -> list[typing.Annotated[numpy.typing.NDArray[numpy.int32], "[3, 3]"]]:
        """
        The rotation parts, in order.
        """
class PointGroupType:
    """
    Metadata for one of the 32 crystallographic point groups. Not the 0D group object.
    """
    def __repr__(self) -> str:
        ...
    @property
    def crystal_class(self) -> CrystalClass:
        ...
    @property
    def holohedry(self) -> Holohedry:
        ...
    @property
    def laue(self) -> Laue:
        ...
    @property
    def number(self) -> int:
        ...
    @property
    def schoenflies(self) -> str:
        ...
    @property
    def symbol(self) -> str:
        ...
class PointgroupNotFoundError(SeitzError):
    """
    The operations match no crystallographic point group.
    """
class SeitzError(Exception):
    """
    Base of every error this library reports. The C++ side returns Result<T> and never throws; this is what that becomes.
    """
class Setting:
    """
    How the input cell maps onto the standardized setting.
    """
    def __repr__(self) -> str:
        ...
    @property
    def origin_shift(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @property
    def rigid_rotation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @property
    def transformation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
class Site:
    """
    The per-atom result of a determination.
    """
    def __repr__(self) -> str:
        ...
    @property
    def equivalent_atom(self) -> int:
        ...
    @property
    def orbit(self) -> int:
        ...
    @property
    def primitive_atom(self) -> int:
        ...
    @property
    def site_symmetry(self) -> str:
        """
        Tabulated site-symmetry symbol.
        """
    @property
    def wyckoff(self) -> int:
        """
        Wyckoff letter index, 0 = 'a'.
        """
class SpaceGroup:
    """
    A space or layer group as a standalone, structure-free object. One shared immutable instance per Hall setting.
    """
    @staticmethod
    def from_number(family: GroupFamily, number: typing.SupportsInt) -> SpaceGroup:
        """
        The group of an international number, in its default Hall setting. 1..230 for space groups, 1..80 for layer groups.
        """
    @staticmethod
    def of(hall: HallNumber) -> SpaceGroup:
        """
        The group of a Hall setting. Total: a HallNumber cannot name a setting that does not exist.
        """
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def wyckoff(self, letter: str) -> typing.Any:
        """
        The position with that letter. Raises if this group has none.
        """
    @property
    def centering(self) -> Centering:
        ...
    @property
    def hall(self) -> HallNumber:
        ...
    @property
    def number(self) -> int:
        ...
    @property
    def operations(self) -> list:
        ...
    @property
    def order(self) -> int:
        """
        Number of operations in the group.
        """
    @property
    def symbol(self) -> str:
        ...
    @property
    def type(self) -> SpacegroupType:
        ...
    @property
    def wyckoffs(self) -> list:
        """
        The Wyckoff positions, ascending by letter; the last is the general position.
        """
class SpacegroupMatch:
    """
    The matched space group of a cell or an operation set.
    """
    @property
    def bravais_lattice(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]"]:
        ...
    @property
    def hall(self) -> HallNumber:
        ...
    @property
    def origin_shift(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @property
    def type(self) -> SpacegroupType:
        ...
class SpacegroupSearchFailedError(SeitzError):
    """
    No Hall setting fits this cell.
    """
class SpacegroupType:
    """
    One Hall setting's metadata. The Hall number itself is not a field: it is the key that addresses the row.
    """
    def __repr__(self) -> str:
        ...
    @property
    def centering(self) -> Centering:
        ...
    @property
    def choice(self) -> str:
        ...
    @property
    def hall_symbol(self) -> str:
        ...
    @property
    def international(self) -> str:
        ...
    @property
    def international_full(self) -> str:
        ...
    @property
    def international_short(self) -> str:
        ...
    @property
    def number(self) -> int:
        """
        International space-group or layer-group number.
        """
    @property
    def pointgroup_number(self) -> int:
        """
        1..32.
        """
    @property
    def schoenflies(self) -> str:
        ...
class SubgroupRelation:
    """
    A maximal-subgroup (or minimal-supergroup) relation: the related space-group number and the prime index of the relation.
    """
    def __repr__(self) -> str:
        ...
    @property
    def index(self) -> int:
        ...
    @property
    def number(self) -> int:
        ...
class SymmetryAnalyzer:
    """
    A persistent view over a cell plus tolerances that lazily computes and memoizes its determination. The object you keep, not a call you repeat. Every const query is thread-safe.
    """
    @staticmethod
    def from_cell(cell: Cell, tolerance: Tolerance = ..., setting: seitz._core.HallNumber | None = None) -> SymmetryAnalyzer:
        """
        An unset `setting` searches every Hall setting of the cell's family; a set one fixes it.
        """
    def __copy__(self) -> typing.Any:
        ...
    def __deepcopy__(self, memo: dict) -> typing.Any:
        ...
    def __repr__(self) -> str:
        ...
    def site_arrays(self) -> dict:
        """
        The per-atom answers as parallel arrays, with no per-site object built. Prefer this to .sites for large cells.
        """
    def standardized_cell_in(self, setting: CellSetting, idealize: bool = True) -> Cell:
        """
        The standardized cell in another setting: conventional or primitive, idealized or keeping the input's own geometry.
        """
    @property
    def cell(self) -> Cell:
        ...
    @property
    def cell_operations(self) -> Operations:
        """
        All operations of the input cell, including the centering translations of a non-primitive cell.
        """
    @property
    def dataset(self) -> Dataset:
        """
        The full determination.
        """
    @property
    def hall(self) -> HallNumber:
        ...
    @property
    def lattice_symmetry(self) -> list:
        """
        The lattice point group: the rotations, in the cell basis, that map the reduced lattice metric onto itself.
        """
    @property
    def operations(self) -> Operations:
        """
        Space-group operations of the input cell as given.
        """
    @property
    def primitive_cell(self) -> Cell:
        ...
    @property
    def sites(self) -> list[Site]:
        ...
    @property
    def spacegroup_type(self) -> SpacegroupType:
        ...
    @property
    def standardized_cell(self) -> Cell:
        """
        The standardized conventional, idealized cell.
        """
    @property
    def tolerance(self) -> Tolerance:
        ...
class SymmetryOperation:
    """
    x -> rotation . x + translation, on fractional coordinates.
    """
    def __copy__(self) -> SymmetryOperation:
        ...
    def __deepcopy__(self, memo: dict) -> SymmetryOperation:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __init__(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.int32, "[3, 3]"] = ..., translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"] = ...) -> None:
        ...
    def __mul__(self, arg0: SymmetryOperation) -> SymmetryOperation:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    def apply(self, x: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @property
    def inverse(self) -> seitz._core.SymmetryOperation | None:
        """
        The inverse, or None when the rotation is not unimodular.
        """
    @property
    def is_identity_rotation(self) -> bool:
        ...
    @property
    def rotation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int32], "[3, 3]"]:
        ...
    @property
    def translation(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
class SymmetryOperationSearchFailedError(SeitzError):
    """
    The search for the cell's symmetry operations failed.
    """
class TimeReversal(enum.IntEnum):
    """
    Whether an operation set includes its time-reversal partners.
    """
    off: typing.ClassVar[TimeReversal]  # value = <TimeReversal.off: 0>
    on: typing.ClassVar[TimeReversal]  # value = <TimeReversal.on: 1>
    @classmethod
    def __new__(cls, value):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
class Tolerance:
    """
    The tolerances threaded through the symmetry search.
    """
    def __init__(self, symprec: typing.SupportsFloat = 1e-05, angle_tolerance: typing.SupportsFloat | None = None) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def angle_tolerance(self) -> float | None:
        ...
    @angle_tolerance.setter
    def angle_tolerance(self, arg0: typing.SupportsFloat | None) -> None:
        ...
    @property
    def symprec(self) -> float:
        ...
    @symprec.setter
    def symprec(self, arg0: typing.SupportsFloat) -> None:
        ...
class UniNumber:
    """
    A validated magnetic space-group (UNI) number, 1..1651.
    """
    @staticmethod
    def of(number: typing.SupportsInt) -> seitz._core.UniNumber | None:
        """
        The number, or None when out of range.
        """
    def __eq__(self, arg0: UniNumber) -> bool:
        ...
    def __ge__(self, arg0: UniNumber) -> bool:
        ...
    def __getstate__(self) -> tuple:
        ...
    def __gt__(self, arg0: UniNumber) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __init__(self, number: typing.SupportsInt) -> None:
        ...
    def __le__(self, arg0: UniNumber) -> bool:
        ...
    def __lt__(self, arg0: UniNumber) -> bool:
        ...
    def __ne__(self, arg0: UniNumber) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple) -> None:
        ...
    @property
    def value(self) -> int:
        ...
class Version:
    """
    A major.minor.patch triple.
    """
    def __repr__(self) -> str:
        ...
    @property
    def major(self) -> int:
        ...
    @property
    def minor(self) -> int:
        ...
    @property
    def patch(self) -> int:
        ...
class Warm(enum.IntFlag):
    """
    Which per-setting caches warmup() should prime.
    """
    layer_groups: typing.ClassVar[Warm]  # value = <Warm.layer_groups: 2>
    space_groups: typing.ClassVar[Warm]  # value = <Warm.space_groups: 1>
    @classmethod
    def __new__(cls, value):
        ...
    def __and__(self, other):
        ...
    def __format__(self, format_spec):
        """
        Convert to a string according to format_spec.
        """
    def __invert__(self):
        ...
    def __or__(self, other):
        ...
    def __rand__(self, other):
        ...
    def __ror__(self, other):
        ...
    def __rxor__(self, other):
        ...
    def __xor__(self, other):
        ...
class Wyckoff:
    """
    One Wyckoff position: an orbit class parameterised by an affine locus in the fractional cell.
    """
    def __repr__(self) -> str:
        ...
    def canonical(self, xyz: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        """
        Project a point onto the locus, so an approximate coordinate still yields the exact orbit.
        """
    def orbit(self, xyz: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"] = ...) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
        """
        The full orbit of `xyz` as an (N, 3) array, one row per image, projected onto the locus first.
        """
    def sample(self, params: collections.abc.Sequence[typing.SupportsFloat]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        """
        A point on the locus from `degrees_of_freedom` free parameters. Extra parameters are ignored.
        """
    @property
    def degrees_of_freedom(self) -> int:
        """
        Free coordinates of the locus, 0..3.
        """
    @property
    def letter(self) -> str:
        """
        Wyckoff letter; 'a' is the most special.
        """
    @property
    def multiplicity(self) -> int:
        ...
    @property
    def operations(self) -> list:
        """
        The site-symmetry group: the operations fixing a generic point.
        """
    @property
    def site_symmetry(self) -> str:
        """
        Tabulated symbol; empty for a derived (point/rod) position.
        """
def all_periodic() -> typing.Annotated[list[AxisKind], "FixedSize(3)"]:
    """
    The fully periodic descriptor: a 3D space-group cell.
    """
def aperiodic_along(axis: typing.SupportsInt) -> typing.Annotated[list[AxisKind], "FixedSize(3)"]:
    """
    Periodic in the plane, aperiodic along `axis` -- a layer.
    """
def aperiodic_axis(periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"]) -> int | None:
    """
    The single aperiodic axis, or None when there is not exactly one.
    """
def conjugated_by(op: SymmetryOperation, t: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], t_inv: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"]) -> SymmetryOperation:
    """
    Change of basis of one operation: (T,0)(R,t)(T,0)^-1.
    """
def default_hall(family: GroupFamily, number: typing.SupportsInt) -> seitz._core.HallNumber | None:
    """
    The default (first) Hall setting of an international number, or None.
    """
def default_halls_with_pointgroup(family: GroupFamily, pointgroup_number: typing.SupportsInt) -> list[int]:
    """
    The default Hall setting index of every group with that point group, ascending by group number.
    """
def family_of(periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"]) -> GroupFamily:
    """
    The family a periodicity puts a cell in.
    """
def halls_with_number(family: GroupFamily, number: typing.SupportsInt) -> list[int]:
    """
    Every Hall setting index of an international number, ascending; empty if out of range.
    """
def minimal_image(diff: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    """
    `diff` folded to its nearest-image residue along every periodic axis.
    """
def none_periodic() -> typing.Annotated[list[AxisKind], "FixedSize(3)"]:
    """
    No periodic axis at all -- a 0D cluster.
    """
def operations_from_database(hall: HallNumber) -> Operations:
    """
    The symmetry operations of a Hall setting.
    """
def periodic_along(axis: typing.SupportsInt) -> typing.Annotated[list[AxisKind], "FixedSize(3)"]:
    """
    Periodic along `axis` only -- a rod.
    """
def pointgroup_by_number(number: typing.SupportsInt) -> PointGroupType:
    """
    Metadata for point group 1..32; number 0 or out of range gives an empty row.
    """
def same_operation(a: SymmetryOperation, b: SymmetryOperation, symprec: typing.SupportsFloat) -> bool:
    """
    Whether two operations agree to within `symprec`. This is the comparison to use -- SymmetryOperation has no __eq__, because an exact float comparison would compete with the library's one definition of equal-within-tolerance.
    """
def spacegroup_type(hall: HallNumber) -> SpacegroupType:
    """
    The metadata of a Hall setting.
    """
def to_positions(rows: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 3]"]:
    """
    Pack a sequence of 3-vectors into an (N, 3) block.
    """
def version_string() -> str:
    """
    "major.minor.patch" of this port.
    """
def warmup(what: Warm = Warm.all) -> None:
    """
    Build the requested per-setting caches ahead of first use. An optimization, never a precondition.
    """
def wrap(vector: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], periodicity: typing.Annotated[collections.abc.Sequence[AxisKind], "FixedSize(3)"]) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
    """
    A fractional coordinate folded into [0, 1) along every periodic axis.
    """
K_DEFAULT_SYMPREC: float = 1e-05
K_LAYER_HALL_SETTINGS: int = 116
K_NUM_LAYER_GROUPS: int = 80
K_NUM_POINTGROUPS: int = 32
K_NUM_SPACEGROUPS: int = 230
K_REFERENCE_SPGLIB_VERSION: Version  # value = Version(2, 7, 0)
K_SPACE_HALL_SETTINGS: int = 530
K_UNI_NUMBERS: int = 1651
K_VERSION: Version  # value = Version(0, 1, 0)
K_ZERO_PREC: float = 1e-10
__version__: str = '0.1.0'
