#include <cppcrystal/group/subgroup_graph.hpp>

#include "core/matrix_order.hpp"
#include <cppcrystal/core/operation_set.hpp>
#include <cppcrystal/core/symmetry_operation.hpp>
#include <cppcrystal/core/tolerance.hpp>
#include <cppcrystal/data/spg_database.hpp>
#include <cppcrystal/data/subgroup_relations.hpp>
#include "generate/random_lattice.hpp"
#include "spacegroup/spacegroup.hpp"

#include <boost/leaf.hpp>

#include <algorithm>
#include <array>
#include <cstdint>
#include <iterator>
#include <optional>
#include <ranges>
#include <set>
#include <tuple>
#include <vector>

namespace cppcrystal::group {

namespace {

// Sets of rotations (point groups and their subgroups) are the library-wide
// RotationSet; a set of those needs an order over sets.
struct RotationSetLess {
  [[nodiscard]] bool operator()(RotationSet const &a,
                                RotationSet const &b) const noexcept {
    return std::ranges::lexicographical_compare(a, b, Matrix3iLess{});
  }
};
using SubgroupSet = std::set<RotationSet, RotationSetLess>;

// The point group of a space group: the distinct rotation parts of its
// conventional operations, in first-occurrence order.
[[nodiscard]] std::vector<Matrix3i>
point_group_rotations(Operations const &ops) {
  return unique_by_rotation(
      ops | std::views::transform(&SymmetryOperation::rotation));
}

// Subgroup generated by a few rotations: close the generators (plus identity)
// under multiplication. Bounded by the crystallographic maximum of 48.
[[nodiscard]] RotationSet closure(std::vector<Matrix3i> const &generators) {
  RotationSet elems;
  std::vector<Matrix3i> mats;
  auto add = [&](Matrix3i const &m) {
    if (elems.insert(m).second) {
      mats.push_back(m);
    }
  };
  add(Matrix3i::Identity());
  std::ranges::for_each(generators, add);
  // Products of every pair, over a list that grows as products are added
  // (so bounds are re-read, not captured in a view).
  for (std::size_t i = 0; i < mats.size(); ++i) {
    for (std::size_t j = 0; j < mats.size(); ++j) {
      add(mats[i] * mats[j]);
      if (mats.size() > 48) {
        return elems; // safety net; a crystallographic group never exceeds 48
      }
    }
  }
  return elems;
}

[[nodiscard]] std::vector<Matrix3i> matrices_of(RotationSet const &s) {
  return {s.begin(), s.end()};
}

// Every subgroup of a point group, by closing the subgroup lattice under join.
// Start from the cyclic subgroups (one generator each), then repeatedly add the
// closure of the union of every pair of known subgroups until no new subgroup
// appears. This reaches subgroups that are not 2-generated (e.g. mmm = Z2^3),
// which a fixed-arity generator scan would miss.
[[nodiscard]] std::vector<RotationSet>
all_subgroups(std::vector<Matrix3i> const &pg) {
  SubgroupSet subs;
  for (auto const &g : pg) {
    subs.insert(closure({g}));
  }

  for (bool changed = true; changed;) {
    changed = false;
    std::vector<RotationSet> const snapshot(subs.begin(), subs.end());
    for (std::size_t a = 0; a < snapshot.size(); ++a) {
      for (std::size_t b = a + 1; b < snapshot.size(); ++b) {
        std::vector<Matrix3i> gens = matrices_of(snapshot[a]);
        std::vector<Matrix3i> const gb = matrices_of(snapshot[b]);
        gens.insert(gens.end(), gb.begin(), gb.end());
        if (subs.insert(closure(gens)).second) {
          changed = true; // a new subgroup appeared; another pass may add more
        }
      }
    }
  }
  return {subs.begin(), subs.end()};
}

// The maximal proper subgroups of a point group: proper subgroups not strictly
// contained in any other proper subgroup.
[[nodiscard]] std::vector<RotationSet>
maximal_point_subgroups(std::vector<Matrix3i> const &pg) {
  std::vector<RotationSet> proper;
  for (auto &s : all_subgroups(pg)) {
    if (s.size() < pg.size()) {
      proper.push_back(std::move(s));
    }
  }
  std::vector<RotationSet> maximal;
  // A proper subgroup is maximal when no other proper subgroup strictly contains
  // it (strict size comparison also excludes the candidate itself).
  for (RotationSet const &candidate : proper) {
    bool const is_maximal =
        std::ranges::none_of(proper, [&](RotationSet const &other) {
          return candidate.size() < other.size() &&
                 std::ranges::includes(other, candidate, Matrix3iLess{});
        });
    if (is_maximal) {
      maximal.push_back(candidate);
    }
  }
  return maximal;
}

// Identify the space-group number generated by a set of operations in
// `lattice`; std::nullopt if the determination fails.
[[nodiscard]] std::optional<int> identify(Operations const &ops,
                                          Matrix3d const &lattice) {
  return boost::leaf::try_handle_all(
      [&]() -> Result<std::optional<int>> {
        auto r = ops.spacegroup(lattice, Tolerance{});
        if (!r) {
          return r.error();
        }
        return std::optional<int>(r->type().number);
      },
      [](boost::leaf::error_info const &) -> std::optional<int> {
        return std::nullopt;
      });
}

} // namespace

// Breadth-first search over the compile-time adjacency: the only part of the
// graph that still needs a runtime walk, since a path is per-query.
std::optional<std::vector<int>> SubgroupGraph::path(int super, int sub) {
  if (!is_subgroup(sub, super)) {
    return std::nullopt;
  }
  if (super == sub) {
    return std::vector<int>{super};
  }

  // predecessor[v] == 0 marks "not yet reached"; space-group numbers start at 1.
  std::array<int, kNumSpaceGroups + 1> predecessor{};
  std::vector<int> queue{super};
  queue.reserve(kNumSpaceGroups);
  for (std::size_t head = 0; head < queue.size(); ++head) {
    int const current = queue[head];
    for (SubgroupRelation const &rel : maximal_subgroups(current)) {
      auto &parent = predecessor[static_cast<std::size_t>(rel.number)];
      if (parent != 0 || rel.number == super) {
        continue;
      }
      parent = current;
      if (rel.number == sub) {
        std::vector<int> chain;
        for (int v = sub; v != super; v = predecessor[static_cast<std::size_t>(v)]) {
          chain.push_back(v);
        }
        chain.push_back(super);
        std::ranges::reverse(chain);
        return chain;
      }
      queue.push_back(rel.number);
    }
  }
  return std::nullopt; // unreachable: is_subgroup already said yes
}

std::vector<TSubgroupEdge> derive_t_subgroup_edges() {
  // For each space group, enumerate the maximal subgroups of its point group;
  // the operations that survive each one form a maximal translationengleiche
  // subgroup, identified back to a space-group number via the determination.
  // One generic conventional lattice per group (deterministic) makes the
  // group's operations exact symmetries and is also invariant under every
  // (lower-symmetry) subgroup.
  std::set<std::tuple<int, int, int>> seen; // (super, sub, index) de-dup
  std::vector<TSubgroupEdge> out;

  for (int const n : std::views::iota(1, kNumSpaceGroups + 1)) {
    auto const hall = data::default_hall<GroupFamily::space>(n);
    if (!hall) {
      continue;
    }
    Operations const &ops = data::operations_from_database(*hall);
    std::vector<Matrix3i> const pg = point_group_rotations(ops);
    Matrix3d const lattice = generate::random_lattice(
        generate::crystal_system(n), 100.0, static_cast<std::uint64_t>(n));

    for (RotationSet const &sub_pg : maximal_point_subgroups(pg)) {
      int const index = static_cast<int>(pg.size() / sub_pg.size());

      // Operations whose rotation survives in the subgroup (all centring copies
      // are retained, so the result is a valid space-group operation set).
      Operations const sub_ops{
          std::from_range,
          ops | std::views::filter([&](SymmetryOperation const &op) {
            return sub_pg.contains(op.rotation);
          })};

      if (std::optional<int> const m = identify(sub_ops, lattice);
          !m || *m == n) {
        continue; // unidentified, or degenerate self-edge
      } else if (seen.insert({n, *m, index}).second) {
        out.push_back(TSubgroupEdge{.super = n, .sub = *m, .index = index});
      }
    }
  }
  return out;
}

} // namespace cppcrystal::group
