#include <cppcrystal/group/subgroup_graph.hpp>

#include <cppcrystal/core/symmetry_operation.hpp>
#include <cppcrystal/core/tolerance.hpp>
#include <cppcrystal/data/spg_database.hpp>
#include <cppcrystal/data/subgroup_relations.hpp>
#include <cppcrystal/generate/random_lattice.hpp>
#include <cppcrystal/spacegroup/spacegroup.hpp>

#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/breadth_first_search.hpp>
#include <boost/graph/transitive_closure.hpp>
#include <boost/graph/visitors.hpp>
#include <boost/leaf.hpp>
#include <boost/property_map/property_map.hpp>

#include <algorithm>
#include <array>
#include <cstdint>
#include <iterator>
#include <numeric>
#include <optional>
#include <ranges>
#include <set>
#include <tuple>
#include <vector>

namespace cppcrystal::group {

namespace {

constexpr int kNumSpaceGroups = 230;

// A rotation matrix flattened to a comparable key, so sets of rotations (point
// groups and their subgroups) can be stored and de-duplicated.
using Key = std::array<int, 9>;
using RotationSet = std::set<Key>;

[[nodiscard]] Key key_of(Matrix3i const &r) noexcept {
  Key k{};
  Eigen::Map<Eigen::Matrix<int, 3, 3, Eigen::RowMajor>>(k.data()) = r;
  return k;
}

[[nodiscard]] Matrix3i matrix_of(Key const &k) noexcept {
  using RowMajorMat3i = Eigen::Matrix<int, 3, 3, Eigen::RowMajor>;
  return Eigen::Map<const RowMajorMat3i>(k.data());
}

// The point group of a space group: the distinct rotation parts of its
// conventional operations.
[[nodiscard]] std::vector<Matrix3i>
point_group_rotations(SymmetryOperations const &ops) {
  RotationSet seen;
  std::vector<Matrix3i> out;
  for (auto const &op : ops) {
    if (seen.insert(key_of(op.rotation)).second) {
      out.push_back(op.rotation);
    }
  }
  return out;
}

// Subgroup generated by a few rotations: close the generators (plus identity)
// under multiplication. Bounded by the crystallographic maximum of 48.
[[nodiscard]] RotationSet closure(std::vector<Matrix3i> const &generators) {
  RotationSet elems;
  std::vector<Matrix3i> mats;
  auto add = [&](Matrix3i const &m) {
    if (elems.insert(key_of(m)).second) {
      mats.push_back(m);
    }
  };
  add(Matrix3i::Identity());
  for (auto const &g : generators) {
    add(g);
  }

  for (std::size_t i = 0; i < mats.size(); ++i) {
    for (std::size_t j = 0; j < mats.size(); ++j) {
      add(mats[i] * mats[j]);
      if (mats.size() > 48) {
        return elems; // safety net; a crystallographic group never exceeds 48
      }
    }
  }
  return elems;
}

[[nodiscard]] std::vector<Matrix3i> matrices_of(RotationSet const &s) {
  std::vector<Matrix3i> out;
  out.reserve(s.size());
  std::ranges::transform(s, std::back_inserter(out), matrix_of);
  return out;
}

// Every subgroup of a point group, by closing the subgroup lattice under join.
// Start from the cyclic subgroups (one generator each), then repeatedly add the
// closure of the union of every pair of known subgroups until no new subgroup
// appears. This reaches subgroups that are not 2-generated (e.g. mmm = Z2^3),
// which a fixed-arity generator scan would miss.
[[nodiscard]] std::vector<RotationSet>
all_subgroups(std::vector<Matrix3i> const &pg) {
  std::set<RotationSet> subs;
  for (auto const &g : pg) {
    subs.insert(closure({g}));
  }

  for (bool changed = true; changed;) {
    changed = false;
    std::vector<RotationSet> const snapshot(subs.begin(), subs.end());
    for (std::size_t a = 0; a < snapshot.size(); ++a) {
      for (std::size_t b = a + 1; b < snapshot.size(); ++b) {
        std::vector<Matrix3i> gens = matrices_of(snapshot[a]);
        std::vector<Matrix3i> const gb = matrices_of(snapshot[b]);
        gens.insert(gens.end(), gb.begin(), gb.end());
        if (subs.insert(closure(gens)).second) {
          changed = true; // a new subgroup appeared; another pass may add more
        }
      }
    }
  }
  return {subs.begin(), subs.end()};
}

// The maximal proper subgroups of a point group: proper subgroups not strictly
// contained in any other proper subgroup.
[[nodiscard]] std::vector<RotationSet>
maximal_point_subgroups(std::vector<Matrix3i> const &pg) {
  std::vector<RotationSet> proper;
  for (auto &s : all_subgroups(pg)) {
    if (s.size() < pg.size()) {
      proper.push_back(std::move(s));
    }
  }
  std::vector<RotationSet> maximal;
  // A proper subgroup is maximal when no other proper subgroup strictly contains
  // it (strict size comparison also excludes the candidate itself).
  for (RotationSet const &candidate : proper) {
    bool const is_maximal =
        std::ranges::none_of(proper, [&](RotationSet const &other) {
          return candidate.size() < other.size() &&
                 std::ranges::includes(other, candidate);
        });
    if (is_maximal) {
      maximal.push_back(candidate);
    }
  }
  return maximal;
}

// Identify the space-group number generated by a set of operations in
// `lattice`; std::nullopt if the determination fails.
[[nodiscard]] std::optional<int> identify(SymmetryOperations const &ops,
                                          Matrix3d const &lattice) {
  return boost::leaf::try_handle_all(
      [&]() -> Result<std::optional<int>> {
        auto r = spacegroup::spacegroup_type_from_symmetry<
            spacegroup::LatticeSetting::conventional>(ops, lattice,
                                                      kDefaultSymprec);
        if (!r) {
          return r.error();
        }
        return std::optional<int>(r->number());
      },
      [](boost::leaf::error_info const &) -> std::optional<int> {
        return std::nullopt;
      });
}

// First (default) Hall setting of an international space-group number. constexpr
// — a pure lookup in the compile-time space-group catalog.
[[nodiscard]] constexpr int default_hall(int number) {
  auto const halls = data::kCatalog.with_number(number);
  return halls.empty() ? 0 : halls.front();
}

} // namespace

struct SubgroupGraph::Impl {
  struct EdgeIndex {
    int index = 0;
  };
  using Graph =
      boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS,
                            boost::no_property, EdgeIndex>;
  // The reachability (transitive-closure) graph carries no edge data — it just
  // records the (super -> sub) pairs of the partial order.
  using Reachability =
      boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS>;

  using Vertex = boost::graph_traits<Graph>::vertex_descriptor;

  Graph graph{static_cast<std::size_t>(kNumSpaceGroups + 1)}; // 0 unused
  Reachability reachability;
  // Maps a vertex of `graph` to the corresponding vertex of `reachability`
  // (the customization point transitive_closure fills in).
  std::vector<Vertex> to_reachability;
};

SubgroupGraph::SubgroupGraph() : impl_(std::make_unique<Impl>()) {
  // Load the baked table (derive_t_subgroup_edges() is the slow offline path
  // that produced it). Cheap — no determination at runtime.
  for (auto const &rel : data::kTSubgroupRelations) {
    boost::add_edge(static_cast<std::size_t>(rel.super),
                    static_cast<std::size_t>(rel.sub),
                    Impl::EdgeIndex{rel.index}, impl_->graph);
  }

  // Precompute the full subgroup partial order once with the specialized
  // transitive_closure algorithm, so is_subgroup() is a direct edge query.
  // The graph->closure vertex correspondence is captured through the g_to_tc
  // property map (a customization point of the algorithm).
  impl_->to_reachability.resize(boost::num_vertices(impl_->graph));
  boost::transitive_closure(
      impl_->graph, impl_->reachability,
      boost::make_iterator_property_map(
          impl_->to_reachability.begin(),
          boost::get(boost::vertex_index, impl_->graph)),
      boost::get(boost::vertex_index, impl_->graph));
}

SubgroupGraph::~SubgroupGraph() = default;

std::vector<TSubgroupEdge> derive_t_subgroup_edges() {
  // For each space group, enumerate the maximal subgroups of its point group;
  // the operations that survive each one form a maximal translationengleiche
  // subgroup, identified back to a space-group number via the determination.
  // One generic conventional lattice per group (deterministic) makes the
  // group's operations exact symmetries and is also invariant under every
  // (lower-symmetry) subgroup.
  std::set<std::tuple<int, int, int>> seen; // (super, sub, index) de-dup
  std::vector<TSubgroupEdge> out;

  for (int const n : std::views::iota(1, kNumSpaceGroups + 1)) {
    int const hall = default_hall(n);
    if (hall == 0) {
      continue;
    }
    SymmetryOperations const &ops = data::operations_from_database(hall);
    std::vector<Matrix3i> const pg = point_group_rotations(ops);
    Matrix3d const lattice = generate::random_lattice(
        generate::crystal_system(n), 100.0, static_cast<std::uint64_t>(n));

    for (RotationSet const &sub_pg : maximal_point_subgroups(pg)) {
      int const index = static_cast<int>(pg.size() / sub_pg.size());

      // Operations whose rotation survives in the subgroup (all centring copies
      // are retained, so the result is a valid space-group operation set).
      SymmetryOperations sub_ops;
      std::ranges::copy_if(ops, std::back_inserter(sub_ops),
                           [&](SymmetryOperation const &op) {
                             return sub_pg.contains(key_of(op.rotation));
                           });

      std::optional<int> const m = identify(sub_ops, lattice);
      if (!m || *m == n) {
        continue; // unidentified, or degenerate self-edge
      }
      if (seen.insert({n, *m, index}).second) {
        out.push_back({n, *m, index});
      }
    }
  }
  return out;
}

SubgroupGraph const &SubgroupGraph::instance() {
  static SubgroupGraph const graph;
  return graph;
}

std::vector<SubgroupRelation>
SubgroupGraph::maximal_subgroups(int number) const {
  std::vector<SubgroupRelation> out;
  if (number < 1 || number > kNumSpaceGroups) {
    return out;
  }
  auto const &g = impl_->graph;
  // Read the edge index through its bundled-property map rather than g[e].
  auto const index = boost::get(&Impl::EdgeIndex::index, g);
  for (auto [it, end] = boost::out_edges(static_cast<std::size_t>(number), g);
       it != end; ++it) {
    out.push_back({static_cast<int>(boost::target(*it, g)), index[*it]});
  }
  return out;
}

std::vector<SubgroupRelation>
SubgroupGraph::minimal_supergroups(int number) const {
  std::vector<SubgroupRelation> out;
  if (number < 1 || number > kNumSpaceGroups) {
    return out;
  }
  auto const &g = impl_->graph;
  auto const index = boost::get(&Impl::EdgeIndex::index, g);
  for (auto [it, end] = boost::in_edges(static_cast<std::size_t>(number), g);
       it != end; ++it) {
    out.push_back({static_cast<int>(boost::source(*it, g)), index[*it]});
  }
  return out;
}

std::optional<std::vector<int>> SubgroupGraph::path(int super, int sub) const {
  if (super < 1 || super > kNumSpaceGroups || sub < 1 ||
      sub > kNumSpaceGroups) {
    return std::nullopt;
  }
  if (super == sub) {
    return std::vector<int>{super};
  }

  auto const &g = impl_->graph;
  using Vertex = boost::graph_traits<Impl::Graph>::vertex_descriptor;

  // breadth_first_search records each vertex's BFS parent into a predecessor
  // property map (a record_predecessors visitor over an iterator property map
  // keyed by the vertex index). A vertex left pointing at itself was unreached.
  std::vector<Vertex> predecessor(boost::num_vertices(g));
  std::iota(predecessor.begin(), predecessor.end(), Vertex{0});
  auto predecessor_map = boost::make_iterator_property_map(
      predecessor.begin(), boost::get(boost::vertex_index, g));

  boost::breadth_first_search(
      g, static_cast<Vertex>(super),
      boost::visitor(boost::make_bfs_visitor(
          boost::record_predecessors(predecessor_map, boost::on_tree_edge()))));

  auto const target = static_cast<Vertex>(sub);
  if (predecessor[target] == target) {
    return std::nullopt; // sub is not reachable from super
  }

  std::vector<int> chain;
  for (Vertex v = target;; v = predecessor[v]) {
    chain.push_back(static_cast<int>(v));
    if (v == static_cast<Vertex>(super)) {
      break;
    }
  }
  std::ranges::reverse(chain);
  return chain;
}

bool SubgroupGraph::is_subgroup(int sub, int super) const {
  if (super < 1 || super > kNumSpaceGroups || sub < 1 ||
      sub > kNumSpaceGroups) {
    return false;
  }
  if (sub == super) {
    return true;
  }
  // A direct lookup in the precomputed transitive closure (no per-call search).
  auto const s = impl_->to_reachability[static_cast<std::size_t>(super)];
  auto const t = impl_->to_reachability[static_cast<std::size_t>(sub)];
  return boost::edge(s, t, impl_->reachability).second;
}

} // namespace cppcrystal::group
