#pragma once

#include <spglib/core/magnetic_symmetry_operation.hpp>
#include <spglib/core/symmetry_operation.hpp>
#include <spglib/data/magnetic_spacegroup_metadata_tables.hpp>
#include <spglib/data/spg_database.hpp> // kNumHallNumbers

#include <array>
#include <cstddef>
#include <optional>
#include <string_view>

// Access to the built-in magnetic space-group database (1651 UNI numbers). The
// raw data tables are generated by tools/transcribe_msg_database.py into two
// headers: data/magnetic_spacegroup_metadata_tables.hpp (catalog metadata + the
// small Hall<->UNI mapping tables, included here to back the constexpr catalog)
// and data/magnetic_spacegroup_operation_tables.hpp (the encoded operations +
// alternative transformations — a compile-time-only compaction, included only
// by the .cpp). This mirrors the non-magnetic spg_database: metadata is decoded
// once at compile time into a constexpr catalog, while the symmetry operations
// (which carry Eigen, not a literal type) are decoded on demand. Port of the
// msgdb_* functions in msg_database.c.
namespace spglib::data {

inline constexpr int kNumUniNumbers = 1651;

// Magnetic space-group type metadata (msg_database.c MagneticSpacegroupType).
struct MagneticSpacegroupType {
  int uni_number = 0;    // 1..1651 (the catalog's unique key)
  int litvin_number = 0; // Litvin's sequential number
  std::string_view bns_number; // Belov-Neronova-Smirnova symbol
  std::string_view og_number;  // Opechowski-Guccione symbol
  int number = 0; // family-space-group international number 1..230
  int type = 0;   // construction type 1..4 (type-I..IV)
};

// A compile-time catalog of the 1651 UNI settings — the magnetic analogue of
// SpacegroupCatalog. Lookup by UNI number is a direct index (UNI numbers are
// the contiguous range 1..1651). Index 0 is a zero-valued sentinel returned for
// out-of-range UNI numbers.
struct MagneticSpacegroupCatalog {
  std::array<MagneticSpacegroupType, kNumUniNumbers + 1> by_uni{};

  [[nodiscard]] constexpr MagneticSpacegroupType const &
  at(int uni) const noexcept {
    bool const in_range = uni >= 1 && uni <= kNumUniNumbers;
    return by_uni[static_cast<std::size_t>(in_range ? uni : 0)];
  }
};

inline constexpr MagneticSpacegroupCatalog kMagneticCatalog = [] {
  MagneticSpacegroupCatalog c{};
  for (std::size_t u = 0; u < kMagneticSpacegroupTypes.size(); ++u) {
    auto const &r = kMagneticSpacegroupTypes[u];
    c.by_uni[u] = MagneticSpacegroupType{r.uni_number, r.litvin_number,
                                         r.bns_number,  r.og_number,
                                         r.number,      r.type};
  }
  return c;
}();

// The type for a UNI number (1..1651); a zero-valued MagneticSpacegroupType if
// out of range. Port of msgdb_get_magnetic_spacegroup_type.
[[nodiscard]] constexpr MagneticSpacegroupType
magnetic_spacegroup_type(int uni_number) noexcept {
  return kMagneticCatalog.at(uni_number);
}

// The {smallest, largest} UNI number whose family space group has the given
// Hall number (1..530); std::nullopt out of range. Port of
// msgdb_get_uni_candidates.
[[nodiscard]] constexpr std::optional<std::array<int, 2>>
uni_candidates(int hall_number) noexcept {
  if (hall_number < 1 || hall_number > kNumHallNumbers) {
    return std::nullopt;
  }
  auto const &m = kMagneticHallMapping[static_cast<std::size_t>(hall_number)];
  return std::array<int, 2>{m[0], m[1]};
}

// The magnetic symmetry operations for a UNI number (1..1651), in the setting
// selected by `hall_number`. `hall_number == 0` uses the smallest Hall setting
// for that UNI (the default). Returns an empty vector if the (UNI, Hall) pair
// is out of range. Port of msgdb_get_spacegroup_operations: the operations are
// decoded from compile-time data on each call (the key space is 2D and sparse,
// so unlike the non-magnetic database there is no per-key cache).
[[nodiscard]] MagneticSymmetryOperations
magnetic_operations_from_database(int uni_number, int hall_number = 0);

// The alternative standardized-setting transformations for a UNI number, in the
// setting selected by `hall_number` (0 = smallest). The identity transformation
// is always the first element. Empty if out of range. Port of
// msgdb_get_std_transformations.
[[nodiscard]] SymmetryOperations
magnetic_std_transformations(int uni_number, int hall_number = 0);

} // namespace spglib::data
