#pragma once

#include <spglib/core/symmetry_operation.hpp>
#include <spglib/core/types.hpp>
#include <spglib/data/spacegroup_metadata_tables.hpp>

#include <algorithm>
#include <array>
#include <cstddef>
#include <span>
#include <string_view>

// Access to the built-in space-group database (530 Hall settings). The raw data
// tables are generated by tools/transcribe_spg_database.py into two headers:
// data/spacegroup_metadata_tables.hpp (plain metadata, included here to back the
// constexpr catalog) and data/spacegroup_operation_tables.hpp (the encoded
// operations — a compile-time-only compaction, included only by the .cpp). Here
// we decode the metadata once at compile time into a constexpr multi-keyed
// catalog, and expose the symmetry operations through a lazily-built cache (the
// ops carry Eigen, which is not a literal type, so they cannot live in a
// constexpr global). Port of the spgdb_* functions in spg_database.c. Layer
// groups are out of scope.
namespace spglib::data {

// Bravais centering (spglib Centering enum).
enum class Centering {
  error,
  primitive,
  body,
  face,
  a_face,
  b_face,
  c_face,
  base,
  r_center,
};

struct SpacegroupType {
  int hall_number = 0; // 1..530 (the catalog's unique key)
  int number = 0;      // international space-group number 1..230
  std::string_view schoenflies;
  std::string_view hall_symbol;
  std::string_view international;
  std::string_view international_full;
  std::string_view international_short;
  std::string_view choice;
  Centering centering = Centering::error;
  int pointgroup_number = 0; // 1..32
};

inline constexpr int kNumHallNumbers = 530;

// A compile-time, multi-keyed catalog of the 530 Hall settings — our own
// constexpr replacement for the boost::multi_index_container. Lookup by Hall
// number is a direct index (Hall numbers are the contiguous range 1..530);
// lookup by international number uses a sorted index permutation with an
// equal_range-style query. Index 0 is a zero-valued sentinel returned for
// out-of-range Hall numbers.
struct SpacegroupCatalog {
  std::array<SpacegroupType, kNumHallNumbers + 1> by_hall{};
  // Hall numbers 1..530 permuted so that by_hall[halls_by_number[i]].number is
  // non-decreasing (ties ordered by Hall number).
  std::array<int, kNumHallNumbers> halls_by_number{};

  // The setting for a Hall number (1..530); the sentinel (number 0) otherwise.
  [[nodiscard]] constexpr SpacegroupType const &at(int hall) const noexcept {
    bool const in_range = hall >= 1 && hall <= kNumHallNumbers;
    return by_hall[static_cast<std::size_t>(in_range ? hall : 0)];
  }

  // Every Hall setting of a given international number, as a span of Hall
  // numbers (empty if none). Mirrors the old ByNumber equal_range.
  [[nodiscard]] constexpr std::span<int const>
  with_number(int number) const noexcept {
    auto const less_n = [this](int hall, int n) {
      return by_hall[static_cast<std::size_t>(hall)].number < n;
    };
    auto const n_less = [this](int n, int hall) {
      return n < by_hall[static_cast<std::size_t>(hall)].number;
    };
    auto const first = std::lower_bound(halls_by_number.begin(),
                                        halls_by_number.end(), number, less_n);
    auto const last = std::upper_bound(halls_by_number.begin(),
                                       halls_by_number.end(), number, n_less);
    return {halls_by_number.data() + (first - halls_by_number.begin()),
            static_cast<std::size_t>(last - first)};
  }
};

// The catalog, decoded from the raw tables at compile time.
inline constexpr SpacegroupCatalog kCatalog = [] {
  SpacegroupCatalog c{};
  for (std::size_t h = 0; h < kSpacegroupTypes.size(); ++h) {
    auto const &r = kSpacegroupTypes[h];
    c.by_hall[h] = SpacegroupType{static_cast<int>(h),
                                  r.number,
                                  r.schoenflies,
                                  r.hall_symbol,
                                  r.international,
                                  r.international_full,
                                  r.international_short,
                                  r.choice,
                                  static_cast<Centering>(r.centering),
                                  r.pointgroup_number};
  }
  for (int i = 0; i < kNumHallNumbers; ++i) {
    c.halls_by_number[static_cast<std::size_t>(i)] = i + 1;
  }
  std::sort(c.halls_by_number.begin(), c.halls_by_number.end(),
            [&c](int a, int b) {
              auto const &ta = c.by_hall[static_cast<std::size_t>(a)];
              auto const &tb = c.by_hall[static_cast<std::size_t>(b)];
              return ta.number != tb.number ? ta.number < tb.number : a < b;
            });
  return c;
}();

// The setting for a Hall number (1..530); a zero-valued SpacegroupType (number
// 0) if out of range. constexpr — usable in constant expressions.
[[nodiscard]] constexpr SpacegroupType
spacegroup_type(int hall_number) noexcept {
  return kCatalog.at(hall_number);
}

// The symmetry operations for a Hall number (1..530); empty if out of range.
// Returns a reference into a lazily-built, immutable per-Hall cache; the
// operations are decoded from compile-time data on first use.
[[nodiscard]] SymmetryOperations const &
operations_from_database(int hall_number);

} // namespace spglib::data
