#!/usr/bin/env python3
"""Generate and narrow the type stub for the seitz._core extension.

Runs pybind11-stubgen and then fixes up what it cannot get right on its own:

  * ``--enum-class-locations`` for every py::native_enum, because a default
    argument of enum type is rendered as its repr (``<Warm.all: 3>``) and
    stubgen needs to be told where the class lives to turn that back into an
    expression.  Without this it exits non-zero.
  * Array annotations, which stubgen writes as a bare ``numpy.ndarray`` that
    tells a type checker nothing.  The library only hands back two dtypes, so
    they become ``numpy.typing.NDArray`` aliases carrying at least that much.
    Shape is not expressible in today's numpy typing; the docstrings say it.

Both halves live here rather than in the CI script so there is one command with
one set of flags, and CI simply diffs the result against the committed stub.

Run it through `uv run`, always. The output depends on the interpreter -- Python
3.10 renders an enum default as `...` where 3.12 renders `Warm.all` -- and CI
regenerates under uv and fails on a diff, so stubs produced by some other python
will fail the gate on an otherwise clean tree.

It imports the module, so PYTHONPATH must point at a build tree -- and if that
tree was built with sanitizers, the same LD_PRELOAD `ctest` sets is needed too,
or the import aborts before stubgen sees anything. Against an ordinary build:

Usage:
    PYTHONPATH=<build>/python uv run python tools/fix_core_stubs.py
"""

import pathlib
import re
import subprocess
import sys

# A package of stubs, not one file: _core has submodules (elements, subgroups),
# so stubgen writes a directory. It sits beside _core.cpython-*.so and does not
# shadow it -- a real module in the same directory wins over a directory with no
# __init__.py -- which is checked by the import in python/tests.
STUB_DIR = pathlib.Path("python/seitz/_core")
MODULE = "seitz._core"
OUT_DIR = "python"

# Every py::native_enum in the bindings. A default argument of one of these
# types cannot be rendered without knowing where the class lives.
ENUMS = (
    "AxisKind",
    "CellSetting",
    "Centering",
    "CrystalClass",
    "GroupFamily",
    "Holohedry",
    "LatticeSetting",
    "Laue",
    "SubgroupKind",
    "TimeReversal",
    "Warm",
)

HEADER = """# Generated by tools/fix_core_stubs.py -- do not edit by hand.
# CI regenerates this and fails on a diff.
"""

SUBSTITUTIONS = (
    (
        r"numpy\.ndarray\[numpy\.float64(?:\[[^\]]*\])*\]",
        "numpy.typing.NDArray[numpy.float64]",
    ),
    (
        r"numpy\.ndarray\[numpy\.int32(?:\[[^\]]*\])*\]",
        "numpy.typing.NDArray[numpy.int32]",
    ),
)


def generate() -> int:
    command = [sys.executable, "-m", "pybind11_stubgen", "-o", OUT_DIR]
    for enum in ENUMS: command += ["--enum-class-locations", f"{enum}:{MODULE}"]
    command.append(MODULE)
    return subprocess.call(command)

def narrow() -> None:
    for stub in sorted(STUB_DIR.rglob("*.pyi")):
        text = stub.read_text()
        for pattern, replacement in SUBSTITUTIONS:
            text = re.sub(pattern, replacement, text)

        if "numpy.typing." in text and "import numpy.typing" not in text:
            if "import numpy\n" in text:
                text = text.replace("import numpy\n", "import numpy\nimport numpy.typing\n", 1)
            else:
                text = "import numpy\nimport numpy.typing\n" + text
        if not text.startswith("# Generated by"):
            text = HEADER + text
        stub.write_text(text)

def main() -> int:
    if generate() != 0:
        print("pybind11-stubgen failed", file=sys.stderr)
        return 1
    if not STUB_DIR.is_dir():
        print(f"{STUB_DIR} was not produced", file=sys.stderr)
        return 1
    narrow()
    print(f"wrote {len(list(STUB_DIR.rglob('*.pyi')))} stub(s) under {STUB_DIR}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
