#!/usr/bin/env python3
"""Generate and narrow the type stub for the seitz._core extension.

Runs pybind11-stubgen and then fixes up what it cannot get right on its own:

  * ``--enum-class-locations`` for every py::native_enum, because a default
    argument of enum type is rendered as its repr (``<Warm.all: 3>``) and
    stubgen needs to be told where the class lives to turn that back into an
    expression.  Without this it exits non-zero.  The list is read off the
    imported module rather than written out here, so a binding that adds an
    enum does not also have to remember to edit this file.
  * Array annotations, which stubgen writes as a bare ``numpy.ndarray`` that
    tells a type checker nothing.  The library only hands back two dtypes, so
    they become ``numpy.typing.NDArray`` aliases carrying at least that much.
    Shape is not expressible in today's numpy typing; the docstrings say it.

Both halves live here rather than in the CI script so there is one command with
one set of flags, and CI simply diffs the result against the committed stub.

Run it through `uv run`, always. The output depends on the interpreter -- Python
3.10 renders an enum default as `...` where 3.12 renders `Warm.all` -- and CI
regenerates under uv and fails on a diff, so stubs produced by some other python
will fail the gate on an otherwise clean tree.

It imports the module, so PYTHONPATH must point at a build tree -- and if that
tree was built with sanitizers, the same LD_PRELOAD `ctest` sets is needed too,
or the import aborts before stubgen sees anything. Against an ordinary build:

Usage:
    PYTHONPATH=<build>/python uv run python tools/fix_core_stubs.py
"""

import enum
import importlib
import inspect
import pathlib
import re
import subprocess
import sys

# A package of stubs, not one file: _core has submodules (elements, subgroups),
# so stubgen writes a directory. It sits beside _core.cpython-*.so and does not
# shadow it -- a real module in the same directory wins over a directory with no
# __init__.py -- which is checked by the import in python/tests.
STUB_DIR = pathlib.Path("python/seitz/_core")
MODULE = "seitz._core"
OUT_DIR = "python"

HEADER = """# Generated by tools/fix_core_stubs.py -- do not edit by hand.
# CI regenerates this and fails on a diff.
"""

SUBSTITUTIONS = (
    (
        r"numpy\.ndarray\[numpy\.float64(?:\[[^\]]*\])*\]",
        "numpy.typing.NDArray[numpy.float64]",
    ),
    (
        r"numpy\.ndarray\[numpy\.int32(?:\[[^\]]*\])*\]",
        "numpy.typing.NDArray[numpy.int32]",
    ),
)


#: enum.Enum, IntEnum, IntFlag and friends: a name in the module's namespace
#: only because the enums it defines derive from it, not something to place.
_ENUM_BASES = frozenset(v for v in vars(enum).values()
                        if isinstance(v, type) and issubclass(v, enum.Enum))


def enum_locations() -> list[str]:
    """``Name:module`` for every enum the extension exports, at any depth.

    A default argument of enum type cannot be rendered without knowing where
    the class lives, and stubgen exits non-zero on the first one it cannot
    place -- so this has to be complete.  Importing the module and asking is
    the only way to keep it that way; the module is imported by stubgen a
    moment later regardless.
    """
    root = importlib.import_module(MODULE)
    submodules = [m for m in vars(root).values()
                  if inspect.ismodule(m) and m.__name__.startswith(f"{MODULE}.")]
    return sorted({f"{name}:{module.__name__}"
                   for module in [root, *submodules]
                   for name, value in vars(module).items()
                   if isinstance(value, type) and issubclass(value, enum.Enum)
                   and value not in _ENUM_BASES})

def generate() -> int:
    locations = enum_locations()
    if not locations:
        print(f"no enums found in {MODULE}; the bindings define several", file=sys.stderr)
        return 1
    command = [sys.executable, "-m", "pybind11_stubgen", "-o", OUT_DIR]
    for location in locations: command += ["--enum-class-locations", location]
    command.append(MODULE)
    return subprocess.call(command)

def narrow() -> None:
    for stub in sorted(STUB_DIR.rglob("*.pyi")):
        text = stub.read_text()
        for pattern, replacement in SUBSTITUTIONS:
            text = re.sub(pattern, replacement, text)

        if "numpy.typing." in text and "import numpy.typing" not in text:
            if "import numpy\n" in text:
                text = text.replace("import numpy\n", "import numpy\nimport numpy.typing\n", 1)
            else:
                text = "import numpy\nimport numpy.typing\n" + text
        if not text.startswith("# Generated by"):
            text = HEADER + text
        stub.write_text(text)

def main() -> int:
    if generate() != 0:
        print("pybind11-stubgen failed", file=sys.stderr)
        return 1
    if not STUB_DIR.is_dir():
        print(f"{STUB_DIR} was not produced", file=sys.stderr)
        return 1
    narrow()
    print(f"wrote {len(list(STUB_DIR.rglob('*.pyi')))} stub(s) under {STUB_DIR}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
