#!/usr/bin/env python3
"""tools/subgroup_relations.csv: the maximal subgroups of the 230 space groups.

    pip install spglib numpy pandas sympy [pyxtal]
    generate_subgroup_relations.py [out.csv]

Edge (G, H, P, s): (a_H b_H c_H) = (a_G b_G c_G) P, x_G = P x_H + s, both in
spglib's first Hall setting; P, s over kTableDenominator. Translationengleiche
edges come from the maximal point subgroups, klassengleiche ones from the
point-group-invariant sublattices of index 2, 3, 4 and the translation
assignments that close; one edge per conjugacy class under G. spglib names each
candidate and its setting; an edge is kept only if every operation of that
setting maps onto an operation of G. PyXtal's tables, if installed, are
diffed at the end (they lack e.g. I422 -> F222).
"""
import dataclasses
import itertools
import sys
import warnings

import numpy as np
import pandas as pd
import spglib
from sympy import Matrix
from sympy.matrices.normalforms import hermite_normal_form

warnings.simplefilter("ignore")
DEN = 24
INDICES = (2, 3, 4)
TOL = 1e-5
COLUMNS = (["super", "hall", "kind", "index"]
           + [f"p{i}{j}" for i in range(3) for j in range(3)] + ["s0", "s1", "s2"])

TYPES = pd.DataFrame(dataclasses.asdict(spglib.get_spacegroup_type(h)) for h in range(1, 531))
TYPES.index = pd.RangeIndex(1, 531, name="hall")
FIRST = TYPES.groupby("number").apply(lambda t: t.index[0])


def ops(hall):
    d = spglib.get_symmetry_from_database(hall)
    return d["rotations"], d["translations"]


def key(R):
    return np.rint(R).astype(np.int8).tobytes()


def in_frame(R, t, Q, q):
    """(R, t) of a frame x = Q x' + q, expressed in the primed frame."""
    Qi = np.linalg.inv(Q)
    return Qi @ R @ Q, (t + np.einsum("nij,j->ni", R, q) - q) @ Qi.T


def reduce(t, basis):
    """t (rows) modulo the lattice spanned by basis's columns."""
    return t - (basis @ np.floor(np.linalg.solve(basis, t.T) + TOL)).T


def subset(RA, tA, RB, tB, lattice=np.eye(3)):
    """Every (RA, tA) is some (RB, tB) modulo the lattice's columns."""
    if not np.allclose(RA, np.rint(RA), atol=TOL):
        return False
    d = np.linalg.solve(lattice, (tA[:, None] - tB[None]).reshape(-1, 3).T).T
    d = np.abs(d - np.rint(d)).reshape(len(RA), len(RB), 3).max(axis=2) < TOL
    same = (np.rint(RA)[:, None] == np.rint(RB)[None]).all(axis=(2, 3))
    return (same & d).any(axis=1).all()


# ---- point groups -----------------------------------------------------------

def closure(gens):
    elems = {key(np.eye(3)): np.eye(3, dtype=int)}
    queue = [np.eye(3, dtype=int)]
    for a in queue:
        for g in gens:
            r = a @ g
            if key(r) not in elems:
                elems[key(r)] = r
                queue.append(r)
    return frozenset(elems)


def maximal_subgroups(pg):
    """Maximal proper subgroups of a point group (sets of rotation keys)."""
    subs = {closure([r]) for r in pg.values()}
    while True:
        joined = {closure([pg[k] for k in a | b]) for a, b in itertools.combinations(subs, 2)}
        if joined <= subs:
            break
        subs |= joined
    proper = [s for s in subs if len(s) < len(pg)]
    return [s for s in proper if not any(s < o for o in proper)]


def conjugacy_classes(subgroups, pg):
    """One representative per class under conjugation by pg."""
    inv = {k: np.rint(np.linalg.inv(r)).astype(int) for k, r in pg.items()}
    seen, out = set(), []
    for s in subgroups:
        canon = min(tuple(sorted(key(pg[g] @ pg[m] @ inv[g]) for m in s)) for g in pg)
        if canon not in seen:
            seen.add(canon)
            out.append(s)
    return out


def generators(pg):
    gens, span = [], closure([])
    for k, r in pg.items():
        if k not in span:
            gens.append(r)
            span = closure(gens)
    return gens


# ---- candidates ---------------------------------------------------------------

@dataclasses.dataclass
class Candidate:
    R: np.ndarray       # one operation per point-group element, G frame
    t: np.ndarray
    basis: np.ndarray   # columns: its translation lattice, G frame
    kind: str
    index: int

    def key(self):
        t = np.rint(reduce(self.t, self.basis) * DEN).astype(int)
        return tuple(sorted(zip(map(key, self.R), map(tuple, t))))


def close(gens, basis, order):
    """Group generated by gens with translations modulo basis: None unless it
    has `order` elements with one consistent translation per rotation."""
    elems = {key(np.eye(3)): (np.eye(3, dtype=int), np.zeros(3))}
    queue = list(elems.values())
    for Ra, ta in queue:
        for Rg, tg in gens:
            R, t = Ra @ Rg, Ra @ tg + ta
            if key(R) in elems:
                d = np.linalg.solve(basis, elems[key(R)][1] - t)
                if not np.allclose(d, np.rint(d), atol=TOL):
                    return None
            else:
                elems[key(R)] = (R, t)
                queue.append((R, t))
                if len(elems) > order:
                    return None
    if len(elems) != order:
        return None
    R, t = zip(*elems.values())
    return np.array(R), reduce(np.array(t), basis)


def hermite_normal_forms(index):
    for d0, d1 in itertools.product(range(1, index + 1), repeat=2):
        if index % (d0 * d1) == 0:
            for a, b, c in itertools.product(range(d0), range(d0), range(d1)):
                yield np.array([[d0, a, b], [0, d1, c], [0, 0, index // (d0 * d1)]])


def cosets(H):
    """Representatives of Z^3 / H Z^3 (rows)."""
    n = np.array(list(itertools.product(*[range(int(abs(H[i]).sum()) + 1) for i in range(3)])))
    return np.unique(np.round(H @ (np.linalg.solve(H, n.T) % 1), 6), axis=1).T


def primitive_basis(R, t):
    """Columns: a basis of the translation lattice (Z^3 plus centring vectors)."""
    pure = np.rint(t[(R == np.eye(3)).all(axis=(1, 2))] * DEN).astype(int)
    hnf = hermite_normal_form(Matrix(np.c_[np.eye(3, dtype=int) * DEN, pure.T]))
    return np.array(hnf, dtype=float)[:, -3:] / DEN


def integral(M):
    return np.allclose(M, np.rint(M), atol=TOL)


def candidates(number):
    R, t = ops(FIRST[number])
    pg = {key(r): r for r in R[np.unique(list(map(key, R)), return_index=True)[1]]}
    rotations = np.array(list(pg.values()))
    out = []
    for sub in conjugacy_classes(maximal_subgroups(pg), pg):
        keep = np.array([key(r) in sub for r in R])
        out.append(Candidate(R[keep], t[keep], np.eye(3), "t", len(pg) // len(sub)))

    representative = {key(r): t[i] for i, r in reversed(list(enumerate(R)))}
    gens = generators(pg)
    B = primitive_basis(R, t)
    index_two = []
    for index in INDICES:
        for H in hermite_normal_forms(index):
            basis = B @ H
            if not integral(np.linalg.solve(basis, rotations @ basis)):
                continue
            shifts = cosets(H) @ B.T
            found = {}
            for choice in itertools.product(range(len(shifts)), repeat=len(gens)):
                closed = close([(g, representative[key(g)] + shifts[c]) for g, c in zip(gens, choice)],
                               basis, len(pg))
                if closed is not None:
                    cand = Candidate(*closed, basis, "k", index)
                    found.setdefault(cand.key(), cand)
            if index == 2:
                index_two += found.values()
            out += [c for c in conjugate_classes(list(found.values()), R, t, shifts)
                    if index != 4 or not any(contained(c, k) for k in index_two)]
    return out


def conjugate_classes(cands, RG, tG, shifts):
    """One candidate per class under conjugation by G (modulo T_H)."""
    seen, out = set(), []
    for c in cands:
        best = None
        for Rg, tg0 in zip(RG, tG):
            Rc = Rg @ c.R @ np.rint(np.linalg.inv(Rg)).astype(int)
            for tg in tg0 + shifts:
                tc = c.t @ Rg.T + tg - np.einsum("nij,j->ni", Rc, tg)
                k = Candidate(Rc, tc, c.basis, c.kind, c.index).key()
                best = k if best is None else min(best, k)
        if best not in seen:
            seen.add(best)
            out.append(c)
    return out


def contained(h, k):
    return integral(np.linalg.solve(k.basis, h.basis)) and subset(h.R, h.t, k.R, k.t, k.basis)


# ---- identification ------------------------------------------------------------

def identify(number, cand):
    """(hall, P, s) of the candidate's first Hall setting, or None."""
    RG, tG = ops(FIRST[number])
    metric = np.einsum("nji,jk,nkl->il", RG, np.diag([1.0, 1.21, 1.69]) + 0.1, RG)
    rows = cand.basis.T @ np.linalg.cholesky(metric)
    R, t = in_frame(cand.R, cand.t, cand.basis, np.zeros(3))
    seeds = [[0.137, 0.291, 0.443], [0.611, 0.053, 0.377], [0.283, 0.719, 0.109]]
    x = ((np.einsum("nij,kj->kni", R, seeds) + t) % 1).reshape(-1, 3)
    cell = (rows, x, np.repeat([0, 1, 2], len(R)))
    found = spglib.get_symmetry_dataset(cell, symprec=TOL)
    hall = FIRST[found.number]
    data = spglib.get_symmetry_dataset(cell, symprec=TOL, hall_number=hall)
    if data is None: return None
    P = cand.basis @ np.linalg.inv(data.transformation_matrix)
    s = P @ ((np.linalg.solve(P, -P @ data.origin_shift)) % 1)
    RH, tH = ops(hall)
    points = lambda R: (R == np.eye(3)).all(axis=(1, 2)).sum()
    lattice_index = cand.index if cand.kind == "k" else 1
    if abs(np.linalg.det(P) * points(RG) - lattice_index * points(RH)) > TOL:
        return None
    if not subset(*in_frame(RH, tH, np.linalg.inv(P), -np.linalg.inv(P) @ s), RG, tG):
        return None
    return hall, P, s

def edges_of(number):
    rows = []
    for cand in candidates(number):
        named = identify(number, cand)
        assert named is not None, f"{number}: unidentified {cand.kind} candidate of index {cand.index}"
        hall, P, s = named
        num = np.r_[P.ravel(), s] * DEN
        assert np.allclose(num, np.rint(num), atol=1e-3), (number, hall)
        rows.append([number, hall, cand.kind, cand.index, *np.rint(num).astype(int)])
    return rows

def pyxtal_diff(df):
    try: from pyxtal.symmetry import Group
    except ImportError: return
    ours = set(map(tuple, df.assign(sub=df.hall.map(TYPES.number))[["super", "sub", "kind", "index"]].to_numpy()))
    theirs = {(n, s, k, i) for n in range(1, 231) for k, table in
              (("t", Group(n).get_max_t_subgroup()), ("k", Group(n).get_max_k_subgroup()))
              for s, i in zip(table["subgroup"], table["index"]) if k == "t" or i in INDICES}
    print("not in PyXtal:", sorted(ours - theirs))
    print("only in PyXtal:", sorted(theirs - ours))

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "tools/subgroup_relations.csv"
    df = pd.DataFrame([r for n in range(1, 231) for r in edges_of(n)], columns=COLUMNS)
    df = df.sort_values(COLUMNS, kind="stable").drop_duplicates()
    df.to_csv(path, index=False)
    print(df.kind.value_counts().to_dict(), "edges written to", path)
    pyxtal_diff(df)

if __name__ == "__main__":
    main()
