// Offline generator for data/subgroup_relations.hpp: re-derives the
// translationengleiche maximal-subgroup graph of the 230 space groups in-house
// (group::derive_t_subgroup_edges) and prints the constexpr table. This is the
// slow path (a determination per candidate subgroup); it is run by hand to
// regenerate the baked table, never as part of the normal build.
//
//   cmake --build <dir> --target generate_subgroup_relations
//   ./generate_subgroup_relations >
//   include/seitz/data/subgroup_relations.hpp
//
#include <seitz/group/subgroup_graph.hpp>

#include <cstdio>

int main() {
  auto const edges = seitz::group::derive_t_subgroup_edges();

  std::printf("#pragma once\n\n");
  std::printf("// GENERATED by tools/generate_subgroup_relations.cpp "
              "(group::derive_t_subgroup_edges).\n");
  std::printf("// Translationengleiche maximal-subgroup edges of the 230 space "
              "groups,\n// derived in-house. Do not edit by hand.\n\n");
  std::printf("#include <array>\n\n");
  std::printf("namespace seitz::data {\n\n");
  std::printf("// One maximal t-subgroup relation: `sub` is a maximal "
              "translationengleiche\n// subgroup of `super` at the given index "
              "(2, 3, or composite, e.g. 4).\n");
  std::printf("struct TSubgroupRelation {\n  int super;\n  int sub;\n  int "
              "index;\n};\n\n");
  std::printf("inline constexpr std::array<TSubgroupRelation, %zu>\n"
              "    kTSubgroupRelations = {{\n",
              edges.size());
  for (auto const &e : edges) {
    std::printf("        {%d, %d, %d},\n", e.super, e.sub, e.index);
  }
  std::printf("}};\n\n");
  std::printf("} // namespace seitz::data\n");
  return 0;
}
