#!/usr/bin/env python3
"""Transcribe spglib's sitesym_database.c data tables into a constexpr header.

The site-symmetry / Wyckoff database is pure generated data:
  - position_wyckoff[]        Wyckoff-position ranges, indexed by Hall number
  - coordinates_first[]       encoded rep coordinate (rot+trans) per Wyckoff pos
  - multiplicities[]          multiplicity per Wyckoff position
  - site_symmetry_symbols[][7] site-symmetry symbol per Wyckoff position

Like the spg_database transcriber, we mechanically convert these into
`inline constexpr std::array`s; the decoder/accessors are hand-written in
src/data/sitesym_database.cpp. Only the 3D arrays are emitted (the layer-group
`position_layer_wyckoff` table is out of scope).

Usage: transcribe_sitesym_database.py <sitesym_database.c> <out.hpp>
"""
import re
import sys


def extract_array_body(text, decl):
    """Return the text between the outermost braces of `decl ... = { ... }`."""
    start = text.index(decl)
    brace = text.index("{", start)
    depth = 0
    i = brace
    in_str = False
    while i < len(text):
        c = text[i]
        if in_str:
            if c == "\\":
                i += 2
                continue
            if c == '"':
                in_str = False
        elif c == '"':
            in_str = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[brace + 1:i]
        i += 1
    raise ValueError("unbalanced braces for " + decl)


def parse_ints(body):
    return [int(x) for x in re.findall(r"-?\d+", body)]


def parse_strings(body):
    # Each entry is a C string literal of exactly 6 visible chars (padded).
    return re.findall(r'"((?:[^"\\]|\\.)*)"', body)


def main():
    src, out = sys.argv[1], sys.argv[2]
    text = open(src).read()

    position_wyckoff = parse_ints(
        extract_array_body(text, "static int const position_wyckoff[]"))
    # Layer-group Wyckoff ranges (negative hall numbers), indexing into the SAME
    # coordinates_first / multiplicities / site_symmetry_symbols arrays.
    position_layer_wyckoff = parse_ints(
        extract_array_body(text, "static int const position_layer_wyckoff[]"))
    coordinates_first = parse_ints(
        extract_array_body(text, "static int const coordinates_first[]"))
    multiplicities = parse_ints(
        extract_array_body(text, "static int const multiplicities[]"))
    # Strip the fixed-width trailing space padding now (spglib does this at
    # runtime via spgdb_remove_space); the emitted table is ready to use.
    symbols = [
        s.rstrip(" ")
        for s in parse_strings(extract_array_body(
            text, "static char const site_symmetry_symbols[][7]"))
    ]

    assert len(coordinates_first) == len(multiplicities) == len(symbols), (
        len(coordinates_first), len(multiplicities), len(symbols))

    with open(out, "w") as f:
        w = f.write
        w("#pragma once\n\n")
        w("// GENERATED by tools/transcribe_sitesym_database.py from spglib\n")
        w("// v2.7.0 sitesym_database.c. Do not edit by hand.\n\n")
        w("#include <array>\n")
        w("#include <string_view>\n\n")
        w("namespace spglib::data {\n\n")

        w("// Wyckoff-position ranges per Hall number: kPositionWyckoff[h] is the\n")
        w("// global index of the first Wyckoff position of Hall number h; the\n")
        w("// count is kPositionWyckoff[h + 1] - kPositionWyckoff[h].\n")
        w("inline constexpr std::array<int, %d> kPositionWyckoff = {{\n"
          % len(position_wyckoff))
        for i in range(0, len(position_wyckoff), 12):
            w("    " + ", ".join(str(x) for x in position_wyckoff[i:i + 12])
              + ",\n")
        w("}};\n\n")

        w("// Layer-group Wyckoff-position ranges, indexed by the negation of the\n")
        w("// (negative) layer hall number; offsets point into the same\n")
        w("// coordinate/multiplicity/symbol arrays as the 3D table.\n")
        w("inline constexpr std::array<int, %d> kPositionLayerWyckoff = {{\n"
          % len(position_layer_wyckoff))
        for i in range(0, len(position_layer_wyckoff), 12):
            w("    " + ", ".join(str(x) for x in position_layer_wyckoff[i:i + 12])
              + ",\n")
        w("}};\n\n")

        w("// Encoded representative coordinate (rotation base-45 + translation\n")
        w("// base-24) per Wyckoff position; see data/sitesym_database.cpp.\n")
        w("inline constexpr std::array<int, %d> kCoordinatesFirst = {{\n"
          % len(coordinates_first))
        for i in range(0, len(coordinates_first), 6):
            w("    " + ", ".join(str(x) for x in coordinates_first[i:i + 6])
              + ",\n")
        w("}};\n\n")

        w("inline constexpr std::array<int, %d> kMultiplicities = {{\n"
          % len(multiplicities))
        for i in range(0, len(multiplicities), 12):
            w("    " + ", ".join(str(x) for x in multiplicities[i:i + 12])
              + ",\n")
        w("}};\n\n")

        w("// Site-symmetry symbols, trailing space padding already removed\n")
        w("// (spglib spgdb_remove_space, applied here at generation time).\n")
        w("inline constexpr std::array<std::string_view, %d> kSiteSymmetrySymbols = {{\n"
          % len(symbols))
        for i in range(0, len(symbols), 6):
            w("    " + ", ".join('"%s"' % s for s in symbols[i:i + 6]) + ",\n")
        w("}};\n\n")

        w("} // namespace spglib::data\n")

    print("position_wyckoff: %d, coordinates_first: %d, multiplicities: %d, "
          "symbols: %d" % (len(position_wyckoff), len(coordinates_first),
                           len(multiplicities), len(symbols)))


if __name__ == "__main__":
    main()
