#!/usr/bin/env python3
"""spglib hall_symbol.c generator / VSpU tables -> constexpr C++.

    transcribe_hall_generators.py <hall_symbol.c> <out.hpp>

Each `static (int|double) NAME[][3][9]` is N settings x 3 rows x 9 values; the
double tables' `2. / 3` expressions evaluate to the same IEEE doubles.
"""
import re
import sys

import numpy as np

from cxx_tables import aggregate, array, c_initializer, epilogue, preamble

def main():
    src, out = sys.argv[1], sys.argv[2]
    text = open(src).read()
    decl = re.compile(r"static\s+(int|double)\s+(\w+)\s*\[\]\s*\[3\]\s*\[9\]\s*=")
    tables = [(name, ctype, np.array(c_initializer(text, name), dtype=ctype)) for ctype, name in decl.findall(text)]
    assert all(t.shape[1:] == (3, 9) for _, _, t in tables)
    with open(out, "w") as f:
        f.write(preamble(["GENERATED by tools/transcribe_hall_generators.py from spglib v2.7.0",
                          "hall_symbol.c. Do not edit by hand. Each table is N x [3][9]: N",
                          "candidate settings, each with 3 generators / VSpU rows of 9 values."]))
        f.write("using GeneratorSet = std::array<std::array<int, 9>, 3>;\n"
                "using VSpUSet = std::array<std::array<double, 9>, 3>;\n\n")
        for name, ctype, table in tables:
            f.write(array(name, "GeneratorSet" if ctype == "int" else "VSpUSet", map(aggregate, table))
                    .replace("inline constexpr", "inline constinit"))
        f.write(epilogue())
    print("transcribed %d tables: %s" % (len(tables), ", ".join(f"{n}[{len(t)}]" for n, _, t in tables)))

if __name__ == "__main__":
    main()
