#!/usr/bin/env python3
"""spglib sitesym_database.c -> the Wyckoff / site-symmetry constexpr tables.

    transcribe_sitesym_database.py <sitesym_database.c> <out.hpp>

position_wyckoff (per Hall number) and position_layer_wyckoff (per negated layer
Hall number) index into the shared coordinates_first / multiplicities /
site_symmetry_symbols arrays; the symbols' fixed-width padding is stripped here.
Decoding lives in src/data/sitesym_database.cpp.
"""
import sys

from cxx_tables import array, c_initializer, epilogue, literal, preamble

def main():
    src, out = sys.argv[1], sys.argv[2]
    text = open(src).read()
    read = lambda name: c_initializer(text, name)
    position, layer = read("position_wyckoff"), read("position_layer_wyckoff")
    first, multiplicity = read("coordinates_first"), read("multiplicities")
    symbols = [s.rstrip(" ") for s in read("site_symmetry_symbols")]
    assert len(first) == len(multiplicity) == len(symbols)
    with open(out, "w") as f:
        f.write(preamble(["GENERATED by tools/transcribe_sitesym_database.py from spglib",
                          "v2.7.0 sitesym_database.c. Do not edit by hand."], ("array", "string_view")))
        f.write(array("kPositionWyckoff", "int", map(str, position), 12,
                      "Wyckoff-position ranges per Hall number: kPositionWyckoff[h] is the\n"
                      "// global index of the first Wyckoff position of Hall number h; the\n"
                      "// count is kPositionWyckoff[h + 1] - kPositionWyckoff[h]."))
        f.write(array("kPositionLayerWyckoff", "int", map(str, layer), 12,
                      "Layer-group Wyckoff-position ranges, indexed by the negation of the\n"
                      "// (negative) layer hall number; offsets point into the same\n"
                      "// coordinate/multiplicity/symbol arrays as the 3D table."))
        f.write(array("kCoordinatesFirst", "int", map(str, first), 6,
                      "Encoded representative coordinate (rotation base-45 + translation\n"
                      "// base-24) per Wyckoff position; see data/sitesym_database.cpp."))
        f.write(array("kMultiplicities", "int", map(str, multiplicity), 12))
        f.write(array("kSiteSymmetrySymbols", "std::string_view", map(literal, symbols), 6,
                      "Site-symmetry symbols, trailing space padding already removed\n"
                      "// (spglib spgdb_remove_space, applied here at generation time)."))
        f.write(epilogue())
    print(f"position_wyckoff: {len(position)}, coordinates_first: {len(first)}, "
          f"multiplicities: {len(multiplicity)}, symbols: {len(symbols)}")


if __name__ == "__main__":
    main()
