#!/usr/bin/env python3
"""Transcribe the curated element reference CSV into a constexpr header.

Unlike the spglib database transcribers, the source here is CppCrystal's own
curated table (tools/element_data.csv: atomic number, symbol, single-bond
covalent radius from Cordero et al. 2008), not a spglib C array. The output
mirrors the same convention: `inline constexpr std::array`s, with the
accessors hand-written (constexpr) in include/cppcrystal/data/element_data.hpp.

Only the covalent radius is tabulated; the atomic volume used to size a
generated cell is derived from it ((4/3) * pi * r^3) at the accessor layer.

Usage: transcribe_elements.py <element_data.csv> <out.hpp>
"""
import csv
import sys


def main():
    src, out = sys.argv[1], sys.argv[2]

    symbols = []
    radii = []
    with open(src) as f:
        for row in csv.reader(f):
            if not row or row[0].lstrip().startswith("#"):
                continue
            z, symbol, radius = int(row[0]), row[1].strip(), float(row[2])
            assert z == len(symbols) + 1, (z, len(symbols))  # contiguous 1..N
            symbols.append(symbol)
            radii.append(radius)

    n = len(symbols)
    with open(out, "w") as f:
        w = f.write
        w("#pragma once\n\n")
        w("// GENERATED by tools/transcribe_elements.py from "
          "tools/element_data.csv\n")
        w("// (single-bond covalent radii, Cordero et al. 2008). "
          "Do not edit by hand.\n\n")
        w("#include <array>\n")
        w("#include <string_view>\n\n")
        w("namespace cppcrystal::data {\n\n")

        w("// Number of tabulated elements (atomic numbers 1..%d).\n" % n)
        w("inline constexpr int kNumElements = %d;\n\n" % n)

        w("// Element symbol indexed by (atomic_number - 1).\n")
        w("inline constexpr std::array<std::string_view, %d> "
          "kElementSymbols = {{\n" % n)
        for i in range(0, n, 10):
            w("    " + ", ".join('"%s"' % s for s in symbols[i:i + 10]) + ",\n")
        w("}};\n\n")

        w("// Single-bond covalent radius (angstrom) indexed by "
          "(atomic_number - 1).\n")
        w("inline constexpr std::array<double, %d> kCovalentRadii = {{\n" % n)
        for i in range(0, n, 8):
            w("    " + ", ".join("%.2f" % r for r in radii[i:i + 8]) + ",\n")
        w("}};\n\n")

        w("} // namespace cppcrystal::data\n")

    print("elements: %d (Z 1..%d)" % (n, n))


if __name__ == "__main__":
    main()
