#!/usr/bin/env python3
"""Transcribe hall_symbol.c's generator / VSpU data tables into constexpr C++.

Each table is `static (int|double) NAME[][3][9] = {...}`. The double tables
contain fraction expressions like `2. / 3`; we evaluate them in Python (float
division yields the identical IEEE double, and repr() round-trips exactly), so
the emitted literals reproduce the reference values bit-for-bit.

Usage: transcribe_hall_generators.py <hall_symbol.c> <out.hpp>
"""
import re
import sys

def extract_body(text, start_brace):
    depth = 0
    for i in range(start_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start_brace:i + 1]
    raise ValueError("unbalanced braces")

def main():
    src, out = sys.argv[1], sys.argv[2]
    text = open(src).read()
    # Strip comments so the eval sees clean data.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)

    decl = re.compile(r"static\s+(int|double)\s+([A-Za-z_]\w*)\s*\[\]\s*\[3\]\s*\[9\]\s*=\s*", re.M)

    tables = []  # (name, ctype, data)  data is N x 3 x 9
    for m in decl.finditer(text):
        ctype, name = m.group(1), m.group(2)
        brace = text.index("{", m.end())
        body = extract_body(text, brace)
        py = body.replace("{", "[").replace("}", "]")
        data = eval(py)  # noqa: S307 - trusted generated input
        assert all(len(e) == 3 and all(len(r) == 9 for r in e) for e in data), name
        tables.append((name, ctype, data))

    with open(out, "w") as fh:
        w = fh.write
        w("#pragma once\n\n")
        w("// GENERATED by tools/transcribe_hall_generators.py from spglib v2.7.0\n")
        w("// hall_symbol.c. Do not edit by hand. Each table is N x [3][9]: N\n")
        w("// candidate settings, each with 3 generators / VSpU rows of 9 values.\n\n")
        w("#include <array>\n\n")
        w("namespace cppcrystal::data {\n\n")
        w("using GeneratorSet = std::array<std::array<int, 9>, 3>;\n")
        w("using VSpUSet = std::array<std::array<double, 9>, 3>;\n\n")

        for (name, ctype, data) in tables:
            elem = "GeneratorSet" if ctype == "int" else "VSpUSet"
            w("inline constinit std::array<%s, %d> %s = {{\n" % (elem, len(data), name))
            for entry in data:
                rows = []
                for row in entry:
                    if ctype == "int":
                        rows.append("{" + ", ".join(str(int(v)) for v in row) + "}")
                    else:
                        rows.append("{" + ", ".join(repr(float(v)) for v in row) + "}")
                w("    {{" + ", ".join(rows) + "}},\n")
            w("}};\n\n")

        w("} // namespace cppcrystal::data\n")

    print("transcribed %d tables: %s" % (len(tables), ", ".join(
        "%s[%d]" % (n, len(d)) for (n, _c, d) in tables)))


if __name__ == "__main__":
    main()
