#!/usr/bin/env python3
"""tools/subgroup_relations.csv -> the maximal-subgroup table.

    transcribe_subgroup_relations.py <subgroup_relations.csv> <out.hpp>

One row per edge of the maximal-subgroup graph of the 230 space groups, derived
offline by tools/generate_subgroup_relations.py: super (number, first Hall
setting), hall (the subgroup's Hall setting), kind (t/k), index, and the
numerators over 24 of P (row-major, (a_H b_H c_H) = (a_G b_G c_G) P) and s
(x_G = P x_H + s, defined modulo P Z^3). Nothing here needs more than pandas.
"""
import sys

import numpy as np
import pandas as pd

from cxx_tables import array, code, epilogue, preamble, struct

DENOMINATOR = 24
KINDS = {"t": "translationengleiche", "k": "klassengleiche"}
P = [f"p{i}{j}" for i in range(3) for j in range(3)]
S = ["s0", "s1", "s2"]

def main():
    src, out = sys.argv[1], sys.argv[2]
    t = pd.read_csv(src)
    assert list(t.columns) == ["super", "hall", "kind", "index", *P, *S], list(t.columns)
    assert t["super"].between(1, 230).all() and t.hall.between(1, 530).all() and t.kind.isin(KINDS).all()
    assert (t["index"] >= 2).all() and t.loc[t.kind == "k", "index"].isin([2, 3, 4]).all()
    assert (np.linalg.det(t[P].to_numpy().reshape(-1, 3, 3)) > 0).all(), "left-handed or singular basis"
    assert not t.duplicated().any(), "duplicate edge"
    t = t.sort_values(list(t.columns), kind="stable")
    with open(out, "w") as f:
        f.write(preamble(["GENERATED by tools/transcribe_subgroup_relations.py from",
                          "tools/subgroup_relations.csv (tools/generate_subgroup_relations.py).",
                          "Do not edit by hand."], ("array", "cstdint"), public=True))
        f.write("// How a maximal subgroup sits in its supergroup: the same lattice and a smaller\n"
                "// point group (translationengleiche), or the same point group and a smaller\n"
                "// lattice (klassengleiche).\n"
                "enum class SubgroupKind : std::uint8_t {\n  translationengleiche,\n  klassengleiche,\n};\n\n"
                "// Denominator of every `basis` and `shift` numerator below.\n"
                f"inline constexpr int kTableDenominator = {DENOMINATOR};\n\n"
                "// One maximal-subgroup relation. `super` is a space-group number in its first\n"
                "// Hall setting; `hall` the Hall setting of the subgroup. The subgroup's\n"
                "// conventional cell in the supergroup's frame: (a_H b_H c_H) = (a_G b_G c_G) . P,\n"
                "// x_G = P x_H + s, with P = basis / kTableDenominator (row-major) and\n"
                "// s = shift / kTableDenominator.\n"
                "struct SubgroupRelation {\n  int super;\n  int hall;\n  SubgroupKind kind;\n  int index;\n"
                "  std::array<int, 9> basis;\n  std::array<int, 3> shift;\n};\n\n")
        rows = (struct([r["super"], r.hall, code(f"SubgroupKind::{KINDS[r.kind]}"), r["index"], list(r[P]), list(r[S])])
                for _, r in t.iterrows())
        f.write(array("kSubgroupRelations", "SubgroupRelation", rows, indent="        "))
        f.write(epilogue(public=True))
    print(f"subgroup edges: {len(t)} (t {(t.kind == 't').sum()}, k {(t.kind == 'k').sum()})")

if __name__ == "__main__":
    main()
