#!/usr/bin/env python3
"""tools/element_data.csv -> constexpr element tables.

    transcribe_elements.py <element_data.csv> <out.hpp>

Covalent radii (Cordero et al. 2008) for every element; metallic and van der
Waals radii (pymatgen, via tools/extract_element_radii.py) where tabulated,
std::nullopt elsewhere. Accessors live in include/seitz/data/element_data.hpp.
"""
import sys

import pandas as pd

from cxx_tables import array, epilogue, literal, preamble

def main():
    src, out = sys.argv[1], sys.argv[2]
    t = pd.read_csv(src, comment="#")
    assert (t.Z == t.index + 1).all(), "atomic numbers must be contiguous from 1"
    optional = lambda col: (None if pd.isna(v) else v for v in t[col])
    with open(out, "w") as f:
        f.write(preamble(["GENERATED by tools/transcribe_elements.py from tools/element_data.csv",
                          "(covalent radii: Cordero et al. 2008; metallic and van der Waals radii:",
                          "pymatgen). Do not edit by hand."], ("array", "optional", "string_view"), public=True))
        f.write(f"// Number of tabulated elements (atomic numbers 1..{len(t)}).\n"
                f"inline constexpr int kNumElements = {len(t)};\n\n")
        f.write(array("kElementSymbols", "std::string_view", map(literal, t.symbol), 10,
                      "Element symbol indexed by (atomic_number - 1)."))
        f.write(array("kCovalentRadii", "double", ("%.2f" % r for r in t.covalent_radius), 8,
                      "Single-bond covalent radius (angstrom) indexed by (atomic_number - 1)."))
        f.write(array("kMetallicRadii", "std::optional<double>",
                      ("std::nullopt" if r is None else "%.2f" % r for r in optional("metallic_radius")), 6,
                      "Metallic radius (angstrom), nullopt where untabulated indexed by (atomic_number - 1)."))
        f.write(array("kVdwRadii", "std::optional<double>",
                      ("std::nullopt" if r is None else "%.2f" % r for r in optional("vdw_radius")), 6,
                      "Van der Waals radius (angstrom), nullopt where untabulated indexed by (atomic_number - 1)."))
        f.write(epilogue(public=True))
    print(f"elements: {len(t)}; metallic {t.metallic_radius.notna().sum()}, vdW {t.vdw_radius.notna().sum()} tabulated")

if __name__ == "__main__":
    main()
