#!/usr/bin/env python3
"""Transcribe tools/rod_group_data.csv into the rod-group constexpr tables.

    transcribe_rod_groups.py <rod_group_data.csv> <out.hpp>

Stdlib only, like every other transcriber the build runs. The CSV is one row per
symmetry operation -- number, HM symbol, 9 row-major rotation entries, 3
translation numerators over kRodTranslationDenominator -- extracted from PyXtal
by tools/extract_rod_groups.py, which is the offline half of this pair.

Operation convention (as in the space-group operation tables): each group holds
one period's worth of factor-group representatives, the pure (0,0,1) lattice
translation being implicit. The periodic axis is c (index 2); a, b are the
aperiodic directions, so the generator's orbit expansion folds the c component
only -- a rod-flipping op sends y -> -y in Cartesian, which must not wrap to
1 - y.
"""
import csv
import sys

NUM_ROD_GROUPS = 75
TRANSLATION_DENOMINATOR = 12
PERIODIC_AXIS = 2  # c


def read_csv(path):
    """(symbols, ops_per_group) for rod groups 1..NUM_ROD_GROUPS."""
    symbols = [None] * NUM_ROD_GROUPS
    ops_per_group = [[] for _ in range(NUM_ROD_GROUPS)]

    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            number = int(row["number"])
            assert 1 <= number <= NUM_ROD_GROUPS, ("rod number", number)
            symbol = row["symbol"]
            if symbols[number - 1] is None:
                symbols[number - 1] = symbol
            assert symbols[number - 1] == symbol, ("symbol drift", number)
            rotation = [int(row["r%d" % i]) for i in range(9)]
            translation = [int(row["t%d" % i]) for i in range(3)]
            assert all(0 <= t < TRANSLATION_DENOMINATOR for t in translation)
            ops_per_group[number - 1].append((rotation, translation))

    missing = [i + 1 for i, s in enumerate(symbols) if s is None]
    assert not missing, ("rod groups absent from the CSV", missing)
    return symbols, ops_per_group


def emit(symbols, ops_per_group, out_path):
    flat = [op for group_ops in ops_per_group for op in group_ops]
    offsets = [0]
    for group_ops in ops_per_group:
        offsets.append(offsets[-1] + len(group_ops))

    with open(out_path, "w") as f:
        w = f.write
        w("#pragma once\n\n")
        w("// GENERATED by tools/transcribe_rod_groups.py from "
          "tools/rod_group_data.csv\n// (PyXtal, via tools/extract_rod_groups"
          ".py). Do not edit by hand.\n\n")
        w("#include <array>\n")
        w("#include <string_view>\n\n")
        w("namespace seitz::data {\n\n")

        w("// Number of rod (1D-periodic subperiodic) groups.\n")
        w("inline constexpr int kNumRodGroups = %d;\n\n" % NUM_ROD_GROUPS)

        w("// Rod groups are 1D-periodic along the c axis (index 2); a, b "
          "(indices 0, 1)\n// are the two aperiodic directions.\n")
        w("inline constexpr int kRodPeriodicAxis = %d;\n\n" % PERIODIC_AXIS)

        w("// Translation components are integer numerators over this "
          "denominator.\n")
        w("inline constexpr int kRodTranslationDenominator = %d;\n\n"
          % TRANSLATION_DENOMINATOR)

        w("// HM symbol indexed by (rod_number - 1).\n")
        w("inline constexpr std::array<std::string_view, kNumRodGroups> "
          "kRodGroupSymbols = {{\n")
        for i in range(0, len(symbols), 5):
            w("    " + ", ".join('"%s"' % s for s in symbols[i:i + 5]) + ",\n")
        w("}};\n\n")

        w("// One symmetry operation: 9 row-major rotation entries + 3 "
          "translation\n// numerators over kRodTranslationDenominator. These are "
          "one period's worth\n// of factor-group representatives (the pure "
          "(0,0,1) lattice translation is\n// implicit), as in the space-group "
          "operation tables.\n")
        w("struct RodOperation {\n")
        w("  std::array<int, 9> rotation;\n")
        w("  std::array<int, 3> translation;\n")
        w("};\n\n")

        w("inline constexpr std::array<RodOperation, %d> kRodOperations = "
          "{{\n" % len(flat))
        for rotation, translation in flat:
            w("    {{%s}, {%s}},\n"
              % (", ".join("%d" % v for v in rotation),
                 ", ".join("%d" % v for v in translation)))
        w("}};\n\n")

        w("// Half-open range [kRodOperationOffset[g-1], kRodOperationOffset[g])"
          "\n// into kRodOperations for rod group g (1..%d).\n"
          % NUM_ROD_GROUPS)
        w("inline constexpr std::array<int, kNumRodGroups + 1> "
          "kRodOperationOffset = {{\n")
        for i in range(0, len(offsets), 12):
            w("    " + ", ".join("%d" % o for o in offsets[i:i + 12]) + ",\n")
        w("}};\n\n")

        w("} // namespace seitz::data\n")

    return len(flat)


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: transcribe_rod_groups.py <rod_group_data.csv> "
                 "<out.hpp>")
    symbols, ops_per_group = read_csv(sys.argv[1])
    total = emit(symbols, ops_per_group, sys.argv[2])
    counts = [len(o) for o in ops_per_group]
    print("rod groups: %d, operations: %d (min %d, max %d per group)"
          % (NUM_ROD_GROUPS, total, min(counts), max(counts)))
    print("written: %s" % sys.argv[2])


if __name__ == "__main__":
    main()
