#!/usr/bin/env python3
"""Transcribe tools/subgroup_relations.csv into the t-subgroup constexpr table.

    transcribe_subgroup_relations.py <subgroup_relations.csv> <out.hpp>

Stdlib only, like every other transcriber the build runs. The CSV is one row per
edge -- super, sub, prime index -- of the translationengleiche maximal-subgroup
graph of the 230 space groups, derived in-house by
tools/generate_subgroup_relations.cpp (group::derive_t_subgroup_edges). That
derivation links this library, whose group/subgroup_graph.hpp includes the header
emitted here, so it stays offline; only this transcription runs per build.
"""
import csv
import sys

NUM_SPACE_GROUPS = 230
PER_LINE = 5


def read_csv(path):
    edges = []
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            super_, sub, index = (int(row["super"]), int(row["sub"]),
                                  int(row["index"]))
            assert 1 <= sub < super_ <= NUM_SPACE_GROUPS, ("edge", row)
            assert index > 1, ("index", row)
            edges.append((super_, sub, index))
    assert edges, "no edges in " + path
    assert edges == sorted(edges), "edges must be sorted by (super, sub, index)"
    return edges


def emit(edges, out_path):
    with open(out_path, "w") as f:
        w = f.write
        w("#pragma once\n\n")
        w("// GENERATED by tools/transcribe_subgroup_relations.py from\n"
          "// tools/subgroup_relations.csv (tools/generate_subgroup_relations"
          ".cpp,\n// group::derive_t_subgroup_edges). Do not edit by hand.\n\n")
        w("#include <array>\n\n")
        w("#pragma GCC visibility push(default)\n\n")
        w("namespace seitz::data {\n\n")
        w("// One maximal t-subgroup relation: `sub` is a maximal "
          "translationengleiche\n// subgroup of `super` at the given index "
          "(2, 3, or composite, e.g. 4).\n")
        w("struct TSubgroupRelation {\n  int super;\n  int sub;\n  int index;"
          "\n};\n\n")
        w("inline constexpr std::array<TSubgroupRelation, %d>\n"
          "    kTSubgroupRelations = {{\n" % len(edges))
        for i in range(0, len(edges), PER_LINE):
            w("        " + " ".join("{%d, %d, %d}," % e
                                    for e in edges[i:i + PER_LINE]) + "\n")
        w("}};\n\n")
        w("} // namespace seitz::data\n\n")
        w("#pragma GCC visibility pop\n")


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: transcribe_subgroup_relations.py "
                 "<subgroup_relations.csv> <out.hpp>")
    edges = read_csv(sys.argv[1])
    emit(edges, sys.argv[2])
    print("t-subgroup edges: %d" % len(edges))
    print("written: %s" % sys.argv[2])


if __name__ == "__main__":
    main()
