#!/usr/bin/env python3
"""spglib msg_database.c -> the magnetic space-group constexpr tables.

    transcribe_msg_database.py <msg_database.c> <metadata_out.hpp> <ops_out.hpp>

Public: magnetic_spacegroup_types plus the Hall<->UNI mappings. Private: the
encoded operations (timerev * 3^9 12^3 + spgdb encoding), the per-setting
{count, start} index and the alternative transformations, both padded to 18
settings (and 7 entries), decoded in src/data/msg_database.cpp.
"""
import sys

import numpy as np

from cxx_tables import aggregate, array, c_initializer, epilogue, preamble, struct

BANNER = ["GENERATED by tools/transcribe_msg_database.py from spglib v2.7.0",
          "msg_database.c. Do not edit by hand.", ""]

def padded(rows, shape):
    """Ragged nested lists into a zero-padded array of the given shape."""
    out = np.zeros(shape, dtype=int)
    for i, row in enumerate(rows):
        for j, entry in enumerate(row):
            out[i, j, :len(entry)] = entry
    return out

def main():
    src, meta_out, ops_out = sys.argv[1:4]
    text = open(src).read()
    read = lambda name: c_initializer(text, name)
    types = read("magnetic_spacegroup_types")
    hall_mapping, uni_mapping = read("magnetic_spacegroup_hall_mapping"), read("magnetic_spacegroup_uni_mapping")
    ops = read("magnetic_symmetry_operations")
    op_index = padded(read("magnetic_spacegroup_operation_index"), (1652, 18, 2))
    alternatives = padded(read("alternative_transformations"), (1652, 18, 7))
    assert (len(types), len(hall_mapping), len(uni_mapping)) == (1652, 531, 1652)

    with open(meta_out, "w") as f:
        f.write(preamble(BANNER + ["Magnetic space-group metadata + the Hall<->UNI mapping tables (no",
                                   "encoded operations) so they can back the constexpr catalog in the",
                                   "public msg_database.hpp without leaking the operation encoding."], public=True))
        f.write("struct MagneticSpacegroupTypeRaw {\n  int uni_number;\n  int litvin_number;\n  char const *bns_number;\n"
                "  char const *og_number;\n  int number;\n  int type;\n};\n\n")
        f.write(array("kMagneticSpacegroupTypes", "MagneticSpacegroupTypeRaw", map(struct, types)))
        f.write(array("kMagneticHallMapping", "std::array<int, 2>", map(aggregate, hall_mapping),
                      comment="Per Hall number (0..530): {smallest UNI number, largest UNI number}\n"
                              "// of the magnetic space groups whose family space group is that Hall #."))
        f.write(array("kMagneticUniMapping", "std::array<int, 2>", map(aggregate, uni_mapping),
                      comment="Per UNI number (0..1651): {number of Hall settings, smallest Hall #}."))
        f.write(epilogue(public=True))

    with open(ops_out, "w") as f:
        f.write(preamble(BANNER + ["Encoded magnetic operations (compile-time-only compaction):",
                                   "  enc = timerev * 34012224 + spgdb_encoded_symmetry,",
                                   "where 34012224 = 3^9 * 12^3. Decoded in src/data/msg_database.cpp;",
                                   "must NOT be included by a public header."]))
        f.write(array("kMagneticOperations", "int", map(str, ops), 8))
        f.write(array("kMagneticOperationIndex", "std::array<std::array<int, 2>, 18>", map(aggregate, op_index),
                      comment="Per [UNI number][Hall-setting offset]: {operation count, start\n"
                              "// index into kMagneticOperations}. Rows padded to 18 with {0, 0}."))
        f.write(array("kAlternativeTransformations", "std::array<std::array<int, 7>, 18>", map(aggregate, alternatives),
                      comment="Per [UNI number][Hall-setting offset]: up to 7 encoded alternative\n"
                              "// transformations (spgdb encoding), zero-terminated; rows padded to 7\n"
                              "// and settings padded to 18 with zeros."))
        f.write(epilogue())
    print(f"types: {len(types)}, hall_mapping: {len(hall_mapping)}, uni_mapping: {len(uni_mapping)}, "
          f"op_index: {len(op_index)}, ops: {len(ops)}, alt: {len(alternatives)}")

if __name__ == "__main__":
    main()
