#!/usr/bin/env python3
"""spglib spg_database.c -> the space-group constexpr tables.

    transcribe_spg_database.py <spg_database.c> <metadata_out.hpp> <ops_out.hpp>

Two headers: the public metadata (spacegroup_types, layer_group_types) and the
private encoded operations (symmetry_operations plus the two {count, start}
index tables), decoded in src/data/spg_database.cpp.
"""
import sys

from cxx_tables import array, c_initializer, epilogue, preamble, struct

CENTERING = {"CENTERING_ERROR": 0, "PRIMITIVE": 1, "BODY": 2, "FACE": 3,
             "A_FACE": 4, "B_FACE": 5, "C_FACE": 6, "BASE": 7, "R_CENTER": 8}
BANNER = ["GENERATED by tools/transcribe_spg_database.py from spglib v2.7.0",
          "spg_database.c. Do not edit by hand.", ""]

def types(rows):
    """(number, six symbols with padding stripped and '=' -> '"' in the Hall symbol, centering, point group)."""
    for number, *symbols, centering, pg in rows:
        symbols = [s.rstrip(" ") for s in symbols]
        symbols[1] = symbols[1].replace("=", '"')
        yield [number, *symbols, centering, pg]

def main():
    src, meta_out, ops_out = sys.argv[1:4]
    text = open(src).read()
    read = lambda name: c_initializer(text, name, CENTERING)
    spacegroups, layers = list(types(read("spacegroup_types")[:531])), list(types(read("layer_group_types")[:117]))
    ops = read("symmetry_operations")
    index, layer_index = read("symmetry_operation_index")[:531], read("layer_symmetry_operation_index")[:117]
    assert (len(spacegroups), len(layers), len(index), len(layer_index)) == (531, 117, 531, 117)

    with open(meta_out, "w") as f:
        f.write(preamble(BANNER + ["Space-group metadata only (no encoded operations) so it can back the",
                                   "constexpr catalog in the public spg_database.hpp without leaking the",
                                   "operation encoding to clients."], public=True))
        f.write("struct SpacegroupTypeRaw {\n  int number;\n  char const *schoenflies;\n  char const *hall_symbol;\n"
                "  char const *international;\n  char const *international_full;\n  char const *international_short;\n"
                "  char const *choice;\n  int centering;\n  int pointgroup_number;\n};\n\n")
        f.write(array("kSpacegroupTypes", "SpacegroupTypeRaw", map(struct, spacegroups)))
        f.write(array("kLayerGroupTypes", "SpacegroupTypeRaw", map(struct, layers),
                      comment="Layer-group metadata (80 layer groups, 117 settings incl. the zero\n"
                              "// sentinel). Indexed by the negation of the (negative) layer hall number."))
        f.write(epilogue(public=True))

    with open(ops_out, "w") as f:
        f.write(preamble(BANNER + ["Encoded symmetry operations (the compile-time-only compaction):",
                                   "rotation base-3, translation base-12. Decoded in",
                                   "src/data/spg_database.cpp; must NOT be included by a public header."]))
        f.write(array("kSymmetryOperations", "int", map(str, ops), 12))
        f.write(array("kSymmetryOperationIndex", "std::array<int, 2>", (f"{{{{{a}, {b}}}}}" for a, b in index)))
        f.write(array("kLayerSymmetryOperationIndex", "std::array<int, 2>", (f"{{{{{a}, {b}}}}}" for a, b in layer_index),
                      comment="Layer-group operation index ({count, offset} into kSymmetryOperations,\n"
                              "// the same shared array). Indexed by -(layer hall number); 117 entries."))
        f.write(epilogue())
    print(f"spacegroup_types: {len(spacegroups)}, symmetry_operations: {len(ops)}, index: {len(index)}, "
          f"layer_group_types: {len(layers)}, layer_index: {len(layer_index)}")

if __name__ == "__main__":
    main()
