#!/usr/bin/env python3
"""tools/rod_group_data.csv -> the rod-group constexpr tables.

    transcribe_rod_groups.py <rod_group_data.csv> <out.hpp>

One row per operation (number, HM symbol, row-major rotation, translation
numerators over kRodTranslationDenominator), extracted from PyXtal by
tools/extract_rod_groups.py. Each group holds one period's factor-group
representatives; the (0,0,1) lattice translation is implicit. c is the periodic
axis, so only that component is ever folded.
"""
import sys

import numpy as np
import pandas as pd

from cxx_tables import array, epilogue, literal, preamble, struct

NUM_ROD_GROUPS = 75
TRANSLATION_DENOMINATOR = 12
PERIODIC_AXIS = 2

def main():
    src, out = sys.argv[1], sys.argv[2]
    t = pd.read_csv(src)
    rotation, translation = [f"r{i}" for i in range(9)], [f"t{i}" for i in range(3)]
    assert t.number.between(1, NUM_ROD_GROUPS).all() and t[translation].isin(range(TRANSLATION_DENOMINATOR)).all().all()
    symbols = t.groupby("number").symbol.agg(lambda s: s.unique().item())   # one symbol per group
    assert list(symbols.index) == list(range(1, NUM_ROD_GROUPS + 1)), "rod groups absent from the CSV"
    counts = t.groupby("number").size()
    offsets = np.r_[0, counts.cumsum()]
    with open(out, "w") as f:
        f.write(preamble(["GENERATED by tools/transcribe_rod_groups.py from tools/rod_group_data.csv",
                          "(PyXtal, via tools/extract_rod_groups.py). Do not edit by hand."],
                         ("array", "string_view")))
        f.write(f"// Number of rod (1D-periodic subperiodic) groups.\ninline constexpr int kNumRodGroups = {NUM_ROD_GROUPS};\n\n"
                "// Rod groups are 1D-periodic along the c axis (index 2); a, b (indices 0, 1)\n"
                f"// are the two aperiodic directions.\ninline constexpr int kRodPeriodicAxis = {PERIODIC_AXIS};\n\n"
                "// Translation components are integer numerators over this denominator.\n"
                f"inline constexpr int kRodTranslationDenominator = {TRANSLATION_DENOMINATOR};\n\n")
        f.write(array("kRodGroupSymbols", "std::string_view", map(literal, symbols), 5,
                      "HM symbol indexed by (rod_number - 1).", size="kNumRodGroups"))
        f.write("// One symmetry operation: 9 row-major rotation entries + 3 translation\n"
                "// numerators over kRodTranslationDenominator. These are one period's worth\n"
                "// of factor-group representatives (the pure (0,0,1) lattice translation is\n"
                "// implicit), as in the space-group operation tables.\n"
                "struct RodOperation {\n  std::array<int, 9> rotation;\n  std::array<int, 3> translation;\n};\n\n")
        f.write(array("kRodOperations", "RodOperation",
                      (struct([r, s]) for r, s in zip(t[rotation].to_numpy(), t[translation].to_numpy()))))
        f.write(array("kRodOperationOffset", "int", map(str, offsets), 12,
                      f"Half-open range [kRodOperationOffset[g-1], kRodOperationOffset[g])\n// into kRodOperations for rod group g (1..{NUM_ROD_GROUPS}).",
                      size="kNumRodGroups + 1"))
        f.write(epilogue())
    print(f"rod groups: {NUM_ROD_GROUPS}, operations: {len(t)} (min {counts.min()}, max {counts.max()} per group)")

if __name__ == "__main__":
    main()
